services:
  bitcredit:
    build: .
    environment:
      - HTTP_ADDRESS=0.0.0.0
      - HTTP_PORT=8001
      - RUST_LOG=info
      - SURREAL_DB_CONNECTION=ws://surrealdb:8000
      - NOSTR_RELAY=wss://bitcr-cloud-run-05-550030097098.europe-west1.run.app
    ports:
      - "8001:8001"
      - "1909:1909"
    depends_on:
      surrealdb:
        condition: service_healthy

  surrealdb:
    image: surrealdb/surrealdb:latest
    volumes:
      - ./data/surrealdb:/data
    command:
      - start
      - --unauthenticated
      - rocksdb:/data/database.db
    user: ${UID}:${GID}
    ports:
      - "8800:8000"
    healthcheck:
      test: [ "CMD", "/surreal", "is-ready" ]
      interval: 5s
      retries: 5
