services:
  bitcredit:
    build: .
    environment:
      - P2P_ADDRESS=0.0.0.0
      - P2P_PORT=1909
      - HTTP_ADDRESS=0.0.0.0
      - HTTP_PORT=8001
      - RUST_LOG=info
      - SURREAL_DB_CONNECTION=ws://surrealdb:8000
      # needs to be replaced with our dev relay later
      - NOSTR_RELAY=ws://relay:8080
    ports:
      - "8001:8001"
      - "1909:1909"
    depends_on:
      - surrealdb
  surrealdb:
    image: surrealdb/surrealdb:latest
    volumes:
      - ./data/surrealdb:/data
    command:
      - start
      - --unauthenticated
      - rocksdb:/data/database.db
    user: ${UID}:${GID}
    ports:
      - "8800:8000"
