// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_ctx`, `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Context>>
abstract class Context implements RustOpaqueInterface {
  ArcBillServiceApi get billService;

  Config get cfg;

  ArcChainKeyServiceApi get chainKeyService;

  ArcCompanyServiceApi get companyService;

  ArcContactServiceApi get contactService;

  ArcFileUploadServiceApi get fileUploadService;

  ArcIdentityServiceApi get identityService;

  ArcMintClientApi get mintClient;

  ArcNostrClient get nostrClient;

  NostrConsumer get nostrConsumer;

  ArcPushApi get pushService;

  ArcSearchServiceApi get searchService;

  ArcTransportServiceApi get transportService;

  set billService(ArcBillServiceApi billService);

  set cfg(Config cfg);

  set chainKeyService(ArcChainKeyServiceApi chainKeyService);

  set companyService(ArcCompanyServiceApi companyService);

  set contactService(ArcContactServiceApi contactService);

  set fileUploadService(ArcFileUploadServiceApi fileUploadService);

  set identityService(ArcIdentityServiceApi identityService);

  set mintClient(ArcMintClientApi mintClient);

  set nostrClient(ArcNostrClient nostrClient);

  set nostrConsumer(NostrConsumer nostrConsumer);

  set pushService(ArcPushApi pushService);

  set searchService(ArcSearchServiceApi searchService);

  set transportService(ArcTransportServiceApi transportService);
}
