// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'data/bill.dart';
import 'data/company.dart';
import 'data/contact.dart';
import 'data/identity.dart';
import 'data/notification.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'data.freezed.dart';

// These functions are ignored because they have generic arguments: `try_map`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `detect_content_type`, `eq`, `extension`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `get_contents`, `len`, `name`, `try_from`, `try_from`, `try_from`, `try_from`, `try_from`, `try_from`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `parse_deadline_string`

class BalanceResponse {
  final String sum;

  const BalanceResponse({required this.sum});

  @override
  int get hashCode => sum.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BalanceResponse &&
          runtimeType == other.runtimeType &&
          sum == other.sum;
}

class Base64FileResponse {
  final String data;
  final String name;
  final String contentType;

  const Base64FileResponse({
    required this.data,
    required this.name,
    required this.contentType,
  });

  @override
  int get hashCode => data.hashCode ^ name.hashCode ^ contentType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Base64FileResponse &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          name == other.name &&
          contentType == other.contentType;
}

class BinaryFileResponse {
  final Uint8List data;
  final String name;
  final String contentType;

  const BinaryFileResponse({
    required this.data,
    required this.name,
    required this.contentType,
  });

  @override
  int get hashCode => data.hashCode ^ name.hashCode ^ contentType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BinaryFileResponse &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          name == other.name &&
          contentType == other.contentType;
}

class BtcAddressAndSumPayload {
  final String billId;
  final String address;
  final String sum;

  const BtcAddressAndSumPayload({
    required this.billId,
    required this.address,
    required this.sum,
  });

  @override
  int get hashCode => billId.hashCode ^ address.hashCode ^ sum.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BtcAddressAndSumPayload &&
          runtimeType == other.runtimeType &&
          billId == other.billId &&
          address == other.address &&
          sum == other.sum;
}

class BtcAddressPayload {
  final String address;

  const BtcAddressPayload({required this.address});

  @override
  int get hashCode => address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BtcAddressPayload &&
          runtimeType == other.runtimeType &&
          address == other.address;
}

class CreateOptionalPostalAddressFfi {
  final String? country;
  final String? city;
  final String? zip;
  final String? address;

  const CreateOptionalPostalAddressFfi({
    this.country,
    this.city,
    this.zip,
    this.address,
  });

  Future<bool> isNone() => RustLib.instance.api
      .crateFfiDataCreateOptionalPostalAddressFfiIsNone(that: this);

  @override
  int get hashCode =>
      country.hashCode ^ city.hashCode ^ zip.hashCode ^ address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateOptionalPostalAddressFfi &&
          runtimeType == other.runtimeType &&
          country == other.country &&
          city == other.city &&
          zip == other.zip &&
          address == other.address;
}

class CreatePostalAddressFfi {
  final String country;
  final String city;
  final String? zip;
  final String address;

  const CreatePostalAddressFfi({
    required this.country,
    required this.city,
    this.zip,
    required this.address,
  });

  @override
  int get hashCode =>
      country.hashCode ^ city.hashCode ^ zip.hashCode ^ address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreatePostalAddressFfi &&
          runtimeType == other.runtimeType &&
          country == other.country &&
          city == other.city &&
          zip == other.zip &&
          address == other.address;
}

class CurrenciesResponse {
  final List<CurrencyResponse> currencies;

  const CurrenciesResponse({required this.currencies});

  @override
  int get hashCode => currencies.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CurrenciesResponse &&
          runtimeType == other.runtimeType &&
          currencies == other.currencies;
}

class CurrencyResponse {
  final String code;

  const CurrencyResponse({required this.code});

  @override
  int get hashCode => code.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CurrencyResponse &&
          runtimeType == other.runtimeType &&
          code == other.code;
}

@freezed
sealed class EditOptionalFieldModeFfi with _$EditOptionalFieldModeFfi {
  const EditOptionalFieldModeFfi._();

  const factory EditOptionalFieldModeFfi.set_(String field0) =
      EditOptionalFieldModeFfi_Set;
  const factory EditOptionalFieldModeFfi.unset() =
      EditOptionalFieldModeFfi_Unset;
  const factory EditOptionalFieldModeFfi.ignore() =
      EditOptionalFieldModeFfi_Ignore;
}

class FileFfi {
  final String name;
  final String hash;
  final String nostrHash;

  const FileFfi({
    required this.name,
    required this.hash,
    required this.nostrHash,
  });

  @override
  int get hashCode => name.hashCode ^ hash.hashCode ^ nostrHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileFfi &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          hash == other.hash &&
          nostrHash == other.nostrHash;
}

class GeneralSearchFilter {
  final String searchTerm;
  final String currency;
  final List<GeneralSearchFilterItemTypeFfi> itemTypes;

  const GeneralSearchFilter({
    required this.searchTerm,
    required this.currency,
    required this.itemTypes,
  });

  @override
  int get hashCode =>
      searchTerm.hashCode ^ currency.hashCode ^ itemTypes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GeneralSearchFilter &&
          runtimeType == other.runtimeType &&
          searchTerm == other.searchTerm &&
          currency == other.currency &&
          itemTypes == other.itemTypes;
}

enum GeneralSearchFilterItemTypeFfi { company, bill, contact }

class GeneralSearchFilterPayload {
  final GeneralSearchFilter filter;

  const GeneralSearchFilterPayload({required this.filter});

  @override
  int get hashCode => filter.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GeneralSearchFilterPayload &&
          runtimeType == other.runtimeType &&
          filter == other.filter;
}

class GeneralSearchResponse {
  final List<LightBitcreditBillFfi> bills;
  final List<ContactFfi> contacts;
  final List<CompanyFfi> companies;

  const GeneralSearchResponse({
    required this.bills,
    required this.contacts,
    required this.companies,
  });

  @override
  int get hashCode => bills.hashCode ^ contacts.hashCode ^ companies.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GeneralSearchResponse &&
          runtimeType == other.runtimeType &&
          bills == other.bills &&
          contacts == other.contacts &&
          companies == other.companies;
}

class LinkToPayResponse {
  final String linkToPay;

  const LinkToPayResponse({required this.linkToPay});

  @override
  int get hashCode => linkToPay.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LinkToPayResponse &&
          runtimeType == other.runtimeType &&
          linkToPay == other.linkToPay;
}

class MempoolLinkResponse {
  final String mempoolLink;

  const MempoolLinkResponse({required this.mempoolLink});

  @override
  int get hashCode => mempoolLink.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MempoolLinkResponse &&
          runtimeType == other.runtimeType &&
          mempoolLink == other.mempoolLink;
}

class NotificationFiltersFfi {
  final bool? active;
  final String? referenceId;
  final String? notificationType;
  final String? level;
  final List<String>? nodeIds;
  final PlatformInt64? limit;
  final PlatformInt64? offset;

  const NotificationFiltersFfi({
    this.active,
    this.referenceId,
    this.notificationType,
    this.level,
    this.nodeIds,
    this.limit,
    this.offset,
  });

  static Future<NotificationFiltersFfi> default_() =>
      RustLib.instance.api.crateFfiDataNotificationFiltersFfiDefault();

  @override
  int get hashCode =>
      active.hashCode ^
      referenceId.hashCode ^
      notificationType.hashCode ^
      level.hashCode ^
      nodeIds.hashCode ^
      limit.hashCode ^
      offset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotificationFiltersFfi &&
          runtimeType == other.runtimeType &&
          active == other.active &&
          referenceId == other.referenceId &&
          notificationType == other.notificationType &&
          level == other.level &&
          nodeIds == other.nodeIds &&
          limit == other.limit &&
          offset == other.offset;
}

class OptionalPostalAddressFfi {
  final String? country;
  final String? city;
  final String? zip;
  final String? address;

  const OptionalPostalAddressFfi({
    this.country,
    this.city,
    this.zip,
    this.address,
  });

  Future<bool> isNone() => RustLib.instance.api
      .crateFfiDataOptionalPostalAddressFfiIsNone(that: this);

  @override
  int get hashCode =>
      country.hashCode ^ city.hashCode ^ zip.hashCode ^ address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OptionalPostalAddressFfi &&
          runtimeType == other.runtimeType &&
          country == other.country &&
          city == other.city &&
          zip == other.zip &&
          address == other.address;
}

class OverviewBalanceResponse {
  final BalanceResponse payee;
  final BalanceResponse payer;
  final BalanceResponse contingent;

  const OverviewBalanceResponse({
    required this.payee,
    required this.payer,
    required this.contingent,
  });

  @override
  int get hashCode => payee.hashCode ^ payer.hashCode ^ contingent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OverviewBalanceResponse &&
          runtimeType == other.runtimeType &&
          payee == other.payee &&
          payer == other.payer &&
          contingent == other.contingent;
}

class OverviewResponse {
  final String currency;
  final OverviewBalanceResponse balances;

  const OverviewResponse({required this.currency, required this.balances});

  @override
  int get hashCode => currency.hashCode ^ balances.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OverviewResponse &&
          runtimeType == other.runtimeType &&
          currency == other.currency &&
          balances == other.balances;
}

class PostalAddressFfi {
  final String country;
  final String city;
  final String? zip;
  final String address;

  const PostalAddressFfi({
    required this.country,
    required this.city,
    this.zip,
    required this.address,
  });

  @override
  int get hashCode =>
      country.hashCode ^ city.hashCode ^ zip.hashCode ^ address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PostalAddressFfi &&
          runtimeType == other.runtimeType &&
          country == other.country &&
          city == other.city &&
          zip == other.zip &&
          address == other.address;
}

class StatusResponse {
  /// Name of the currently configured Bitcoin network (e.g. `mainnet`, `testnet`).
  final String bitcoinNetwork;

  /// `true` if the app has an active connection to at least one configured Nostr relay.
  ///
  /// This reflects the status of the Nostr transport layer, not general internet
  /// connectivity or backend/database availability. When `connected` is `false`,
  /// operations that require Nostr (such as bill synchronization with other peers,
  /// sending or receiving notifications, or other relay-based messaging) will not
  /// be able to communicate over the network and may fall back to local-only state.
  final bool connected;

  /// Semantic version of the running E-Bills application backend.
  final String appVersion;

  const StatusResponse({
    required this.bitcoinNetwork,
    required this.connected,
    required this.appVersion,
  });

  @override
  int get hashCode =>
      bitcoinNetwork.hashCode ^ connected.hashCode ^ appVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatusResponse &&
          runtimeType == other.runtimeType &&
          bitcoinNetwork == other.bitcoinNetwork &&
          connected == other.connected &&
          appVersion == other.appVersion;
}

class UploadFile {
  final Uint8List data;
  final String? extension_;
  final String name;

  const UploadFile({required this.data, this.extension_, required this.name});

  @override
  int get hashCode => data.hashCode ^ extension_.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UploadFile &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          extension_ == other.extension_ &&
          name == other.name;
}

class UploadFileResponse {
  final String fileUploadId;

  const UploadFileResponse({required this.fileUploadId});

  @override
  int get hashCode => fileUploadId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UploadFileResponse &&
          runtimeType == other.runtimeType &&
          fileUploadId == other.fileUploadId;
}
