// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `bill_service_error_data`, `err_400`, `err_404`, `err_500`, `notification_service_error_data`, `protocol_validation_error_data`, `validation_error_data`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

class EbillFfiError implements FrbException {
  final EbillFfiErrorKind kind;
  final EbillFfiErrorCode code;
  final String msg;

  const EbillFfiError({
    required this.kind,
    required this.code,
    required this.msg,
  });

  @override
  int get hashCode => kind.hashCode ^ code.hashCode ^ msg.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EbillFfiError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          code == other.code &&
          msg == other.msg;
}

enum EbillFfiErrorCode {
  fieldEmpty,
  fieldInvalid,
  invalidSum,
  invalidCurrency,
  invalidBitcoinAddress,
  invalidBitcoinDescriptor,
  invalidContentType,
  identityCantBeAnon,
  invalidContactType,
  invalidIdentityType,
  invalidDate,
  invalidCountry,
  invalidTimestamp,
  deadlineBeforeMinimum,
  selfDraftedBillCantBeBlank,
  requestToMintForBillAndMintAlreadyActive,
  signerCantBeAnon,
  contactIsAnonymous,
  invalidContact,
  invalidMint,
  issueDateAfterMaturityDate,
  maturityDateInThePast,
  requestToPayBeforeMaturityDate,
  invalidFileUploadId,
  invalidNodeId,
  invalidBillId,
  invalidBillType,
  draweeCantBePayee,
  endorserCantBeEndorsee,
  buyerCantBeSeller,
  recourserCantBeRecoursee,
  draweeNotInContacts,
  payeeNotInContacts,
  mintNotInContacts,
  buyerNotInContacts,
  endorseeNotInContacts,
  recourseeNotInContacts,
  noPaymentForSweep,
  cancelMintRequestNotPending,
  rejectMintRequestNotOffered,
  acceptMintRequestNotOffered,
  acceptMintOfferExpired,
  noConfirmedEmailForIdentIdentity,
  noFileForFileUploadId,
  notFound,
  externalApi,
  crypto,
  persistence,
  blockchain,
  protocol,
  invalidRelayUrl,
  serialization,
  init,
  notificationNetwork,
  notificationMessage,
  invalidOperation,
  billAlreadyAccepted,
  billWasRejectedToAccept,
  billAcceptanceExpired,
  billWasRejectedToPay,
  billPaymentExpired,
  billWasRecoursedToTheEnd,
  billAlreadyRequestedToAccept,
  billNotAccepted,
  callerIsNotDrawee,
  callerIsNotHolder,
  callerIsNotRecoursee,
  callerIsNotBuyer,
  requestAlreadyRejected,
  billAlreadyPaid,
  billWasNotRequestedToPay,
  billWasNotOfferedToSell,
  billRequestToAcceptDidNotExpireAndWasNotRejected,
  billRequestToPayDidNotExpireAndWasNotRejected,
  recourseeNotPastHolder,
  billWasNotRequestedToRecourse,
  billIsNotRequestedToRecourseAndWaitingForPayment,
  billIsNotOfferToSellWaitingForPayment,
  billSellDataInvalid,
  billRecourseDataInvalid,
  billIsRequestedToPayAndWaitingForPayment,
  billIsOfferedToSellAndWaitingForPayment,
  billIsInRecourseAndWaitingForPayment,
  signatoryNotInContacts,
  signatoryAlreadySignatory,
  cantRemoveLastSignatory,
  notASignatory,
  notARemovedOrRejectedSignatory,
  notInvitedAsSignatory,
  noSignerIdentityProof,
  fileIsTooBig,
  fileIsEmpty,
  tooManyFiles,
  invalidFileName,
  unknownNodeId,
  callerMustBeSignatory,
  callerMustBeCreator,
  callerMustBeIdentifiedCreator,
  invalidIdentityProof,
  invalidReferenceBlock,
  mintRequestToPayWithoutCustomAddress,
  invalidSignature,
  invalidHash,
  invalidUrl,
  invalidIdentityProofStatus,
  json,
  invalidBillAction,
  invalidCompanyAction,
  invalidIdentityAction,
  companySignerCreatorMismatch,
  invalidMintRequestId,
}

enum EbillFfiErrorKind {
  badRequest,
  notFound,
  network,
  internal,
  initialization,
  unavailable,
  unsupported,
}
