// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'ffi/error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `init_logging`, `init_panic_hook`, `new`, `reset_runtime`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EbillRuntime`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `get_last_contact_publish_check`, `is_transport_connected`, `set_last_contact_publish_check`, `set_transport_connected`

Future<void> initEbillFfi({required EbillConfig conf}) =>
    RustLib.instance.api.crateFfiInitEbillFfi(conf: conf);

class EbillConfig {
  final String dbFolderPath;
  final String dbFolderPathFiles;
  final String? logLevel;
  final String bitcoinNetwork;
  final List<String> esploraBaseUrls;
  final List<String> nostrRelays;
  final List<String>? blossomServers;
  final bool? nostrOnlyKnownContacts;
  final BigInt? nostrMaxRelays;
  final BigInt? nostrRelayAckThreshold;
  final BigInt jobRunnerInitialDelaySeconds;
  final BigInt jobRunnerCheckIntervalSeconds;
  final int? transportInitialSubscriptionDelaySeconds;
  final String defaultMintUrl;
  final String defaultMintNodeId;
  final BigInt numConfirmationsForPayment;
  final bool devMode;
  final bool mandatoryEmailConfirmations;
  final String defaultCourtUrl;

  const EbillConfig({
    required this.dbFolderPath,
    required this.dbFolderPathFiles,
    this.logLevel,
    required this.bitcoinNetwork,
    required this.esploraBaseUrls,
    required this.nostrRelays,
    this.blossomServers,
    this.nostrOnlyKnownContacts,
    this.nostrMaxRelays,
    this.nostrRelayAckThreshold,
    required this.jobRunnerInitialDelaySeconds,
    required this.jobRunnerCheckIntervalSeconds,
    this.transportInitialSubscriptionDelaySeconds,
    required this.defaultMintUrl,
    required this.defaultMintNodeId,
    required this.numConfirmationsForPayment,
    required this.devMode,
    required this.mandatoryEmailConfirmations,
    required this.defaultCourtUrl,
  });

  @override
  int get hashCode =>
      dbFolderPath.hashCode ^
      dbFolderPathFiles.hashCode ^
      logLevel.hashCode ^
      bitcoinNetwork.hashCode ^
      esploraBaseUrls.hashCode ^
      nostrRelays.hashCode ^
      blossomServers.hashCode ^
      nostrOnlyKnownContacts.hashCode ^
      nostrMaxRelays.hashCode ^
      nostrRelayAckThreshold.hashCode ^
      jobRunnerInitialDelaySeconds.hashCode ^
      jobRunnerCheckIntervalSeconds.hashCode ^
      transportInitialSubscriptionDelaySeconds.hashCode ^
      defaultMintUrl.hashCode ^
      defaultMintNodeId.hashCode ^
      numConfirmationsForPayment.hashCode ^
      devMode.hashCode ^
      mandatoryEmailConfirmations.hashCode ^
      defaultCourtUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EbillConfig &&
          runtimeType == other.runtimeType &&
          dbFolderPath == other.dbFolderPath &&
          dbFolderPathFiles == other.dbFolderPathFiles &&
          logLevel == other.logLevel &&
          bitcoinNetwork == other.bitcoinNetwork &&
          esploraBaseUrls == other.esploraBaseUrls &&
          nostrRelays == other.nostrRelays &&
          blossomServers == other.blossomServers &&
          nostrOnlyKnownContacts == other.nostrOnlyKnownContacts &&
          nostrMaxRelays == other.nostrMaxRelays &&
          nostrRelayAckThreshold == other.nostrRelayAckThreshold &&
          jobRunnerInitialDelaySeconds == other.jobRunnerInitialDelaySeconds &&
          jobRunnerCheckIntervalSeconds ==
              other.jobRunnerCheckIntervalSeconds &&
          transportInitialSubscriptionDelaySeconds ==
              other.transportInitialSubscriptionDelaySeconds &&
          defaultMintUrl == other.defaultMintUrl &&
          defaultMintNodeId == other.defaultMintNodeId &&
          numConfirmationsForPayment == other.numConfirmationsForPayment &&
          devMode == other.devMode &&
          mandatoryEmailConfirmations == other.mandatoryEmailConfirmations &&
          defaultCourtUrl == other.defaultCourtUrl;
}
