// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'ffi.dart';
import 'ffi/api/bill.dart';
import 'ffi/api/company.dart';
import 'ffi/api/contact.dart';
import 'ffi/api/general.dart';
import 'ffi/api/identity.dart';
import 'ffi/api/notification.dart';
import 'ffi/data.dart';
import 'ffi/data/bill.dart';
import 'ffi/data/company.dart';
import 'ffi/data/contact.dart';
import 'ffi/data/identity.dart';
import 'ffi/data/mint.dart';
import 'ffi/data/notification.dart';
import 'ffi/error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  FutureOr<void> Function(NotificationSubscriptionResponse)
  dco_decode_DartFn_Inputs_notification_subscription_response_Output_unit_AnyhowException(
    dynamic raw,
  );

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AcceptBitcreditBillPayload dco_decode_accept_bitcredit_bill_payload(
    dynamic raw,
  );

  @protected
  AcceptCompanyInvitePayload dco_decode_accept_company_invite_payload(
    dynamic raw,
  );

  @protected
  ApproveContactSharePayload dco_decode_approve_contact_share_payload(
    dynamic raw,
  );

  @protected
  BalanceResponse dco_decode_balance_response(dynamic raw);

  @protected
  Base64FileResponse dco_decode_base_64_file_response(dynamic raw);

  @protected
  BillAcceptStateFfi dco_decode_bill_accept_state_ffi(dynamic raw);

  @protected
  BillAcceptanceStatusFfi dco_decode_bill_acceptance_status_ffi(dynamic raw);

  @protected
  BillAnonParticipantFfi dco_decode_bill_anon_participant_ffi(dynamic raw);

  @protected
  BillCallerActionsFfi dco_decode_bill_caller_actions_ffi(dynamic raw);

  @protected
  BillCallerBillActionFfi dco_decode_bill_caller_bill_action_ffi(dynamic raw);

  @protected
  BillCallerPaymentActionFfi dco_decode_bill_caller_payment_action_ffi(
    dynamic raw,
  );

  @protected
  BillCallerPaymentFfi dco_decode_bill_caller_payment_ffi(dynamic raw);

  @protected
  BillCallerPaymentStateFfi dco_decode_bill_caller_payment_state_ffi(
    dynamic raw,
  );

  @protected
  BillCheckSweepBTCFundsPayload dco_decode_bill_check_sweep_btc_funds_payload(
    dynamic raw,
  );

  @protected
  BillCombinedBitcoinKeyFfi dco_decode_bill_combined_bitcoin_key_ffi(
    dynamic raw,
  );

  @protected
  BillCurrentWaitingStateFfi dco_decode_bill_current_waiting_state_ffi(
    dynamic raw,
  );

  @protected
  BillDataFfi dco_decode_bill_data_ffi(dynamic raw);

  @protected
  BillHistoryBlockFfi dco_decode_bill_history_block_ffi(dynamic raw);

  @protected
  BillHistoryBlockPaymentDataFfi dco_decode_bill_history_block_payment_data_ffi(
    dynamic raw,
  );

  @protected
  BillHistoryResponse dco_decode_bill_history_response(dynamic raw);

  @protected
  BillIdResponse dco_decode_bill_id_response(dynamic raw);

  @protected
  BillIdentParticipantFfi dco_decode_bill_ident_participant_ffi(dynamic raw);

  @protected
  BillMintStateFfi dco_decode_bill_mint_state_ffi(dynamic raw);

  @protected
  BillMintStatusFfi dco_decode_bill_mint_status_ffi(dynamic raw);

  @protected
  BillOpCodeFfi dco_decode_bill_op_code_ffi(dynamic raw);

  @protected
  BillParticipantFfi dco_decode_bill_participant_ffi(dynamic raw);

  @protected
  BillParticipantsFfi dco_decode_bill_participants_ffi(dynamic raw);

  @protected
  BillPaymentStateFfi dco_decode_bill_payment_state_ffi(dynamic raw);

  @protected
  BillPaymentStatusFfi dco_decode_bill_payment_status_ffi(dynamic raw);

  @protected
  BillRecourseStatusFfi dco_decode_bill_recourse_status_ffi(dynamic raw);

  @protected
  BillSellStatusFfi dco_decode_bill_sell_status_ffi(dynamic raw);

  @protected
  BillStateFfi dco_decode_bill_state_ffi(dynamic raw);

  @protected
  BillStatusFfi dco_decode_bill_status_ffi(dynamic raw);

  @protected
  BillSweepBTCEstimateFfi dco_decode_bill_sweep_btc_estimate_ffi(dynamic raw);

  @protected
  BillSweepBTCFundsPayload dco_decode_bill_sweep_btc_funds_payload(dynamic raw);

  @protected
  BillSweepBTCFundsResultFfi dco_decode_bill_sweep_btc_funds_result_ffi(
    dynamic raw,
  );

  @protected
  BillSweepBTCOptionFfi dco_decode_bill_sweep_btc_option_ffi(dynamic raw);

  @protected
  BillWaitingForPaymentStateFfi dco_decode_bill_waiting_for_payment_state_ffi(
    dynamic raw,
  );

  @protected
  BillWaitingForRecourseStateFfi dco_decode_bill_waiting_for_recourse_state_ffi(
    dynamic raw,
  );

  @protected
  BillWaitingForSellStateFfi dco_decode_bill_waiting_for_sell_state_ffi(
    dynamic raw,
  );

  @protected
  BillWaitingStatePaymentDataFfi dco_decode_bill_waiting_state_payment_data_ffi(
    dynamic raw,
  );

  @protected
  BillsFilterRoleFfi dco_decode_bills_filter_role_ffi(dynamic raw);

  @protected
  BillsResponse dco_decode_bills_response(dynamic raw);

  @protected
  BillsSearchFilter dco_decode_bills_search_filter(dynamic raw);

  @protected
  BillsSearchFilterPayload dco_decode_bills_search_filter_payload(dynamic raw);

  @protected
  BinaryFileResponse dco_decode_binary_file_response(dynamic raw);

  @protected
  BitcreditBillFfi dco_decode_bitcredit_bill_ffi(dynamic raw);

  @protected
  BitcreditBillPayload dco_decode_bitcredit_bill_payload(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AcceptBitcreditBillPayload
  dco_decode_box_autoadd_accept_bitcredit_bill_payload(dynamic raw);

  @protected
  AcceptCompanyInvitePayload
  dco_decode_box_autoadd_accept_company_invite_payload(dynamic raw);

  @protected
  ApproveContactSharePayload
  dco_decode_box_autoadd_approve_contact_share_payload(dynamic raw);

  @protected
  BillAnonParticipantFfi dco_decode_box_autoadd_bill_anon_participant_ffi(
    dynamic raw,
  );

  @protected
  BillCallerPaymentFfi dco_decode_box_autoadd_bill_caller_payment_ffi(
    dynamic raw,
  );

  @protected
  BillCallerPaymentStateFfi
  dco_decode_box_autoadd_bill_caller_payment_state_ffi(dynamic raw);

  @protected
  BillCheckSweepBTCFundsPayload
  dco_decode_box_autoadd_bill_check_sweep_btc_funds_payload(dynamic raw);

  @protected
  BillCurrentWaitingStateFfi
  dco_decode_box_autoadd_bill_current_waiting_state_ffi(dynamic raw);

  @protected
  BillHistoryBlockPaymentDataFfi
  dco_decode_box_autoadd_bill_history_block_payment_data_ffi(dynamic raw);

  @protected
  BillIdentParticipantFfi dco_decode_box_autoadd_bill_ident_participant_ffi(
    dynamic raw,
  );

  @protected
  BillParticipantFfi dco_decode_box_autoadd_bill_participant_ffi(dynamic raw);

  @protected
  BillSweepBTCFundsPayload dco_decode_box_autoadd_bill_sweep_btc_funds_payload(
    dynamic raw,
  );

  @protected
  BillWaitingForPaymentStateFfi
  dco_decode_box_autoadd_bill_waiting_for_payment_state_ffi(dynamic raw);

  @protected
  BillWaitingForRecourseStateFfi
  dco_decode_box_autoadd_bill_waiting_for_recourse_state_ffi(dynamic raw);

  @protected
  BillWaitingForSellStateFfi
  dco_decode_box_autoadd_bill_waiting_for_sell_state_ffi(dynamic raw);

  @protected
  BillsSearchFilterPayload dco_decode_box_autoadd_bills_search_filter_payload(
    dynamic raw,
  );

  @protected
  BitcreditBillPayload dco_decode_box_autoadd_bitcredit_bill_payload(
    dynamic raw,
  );

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  BtcAddressAndSumPayload dco_decode_box_autoadd_btc_address_and_sum_payload(
    dynamic raw,
  );

  @protected
  BtcAddressPayload dco_decode_box_autoadd_btc_address_payload(dynamic raw);

  @protected
  ChangeIdentityEmailPayload
  dco_decode_box_autoadd_change_identity_email_payload(dynamic raw);

  @protected
  ChangeIdentityPayload dco_decode_box_autoadd_change_identity_payload(
    dynamic raw,
  );

  @protected
  ChangeSignatoryEmailPayload
  dco_decode_box_autoadd_change_signatory_email_payload(dynamic raw);

  @protected
  CompanyConfirmEmailPayload
  dco_decode_box_autoadd_company_confirm_email_payload(dynamic raw);

  @protected
  CompanyVerifyEmailPayload dco_decode_box_autoadd_company_verify_email_payload(
    dynamic raw,
  );

  @protected
  ConfirmEmailPayload dco_decode_box_autoadd_confirm_email_payload(dynamic raw);

  @protected
  CreateCompanyPayload dco_decode_box_autoadd_create_company_payload(
    dynamic raw,
  );

  @protected
  CreateOptionalPostalAddressFfi
  dco_decode_box_autoadd_create_optional_postal_address_ffi(dynamic raw);

  @protected
  CreatePostalAddressFfi dco_decode_box_autoadd_create_postal_address_ffi(
    dynamic raw,
  );

  @protected
  DateRange dco_decode_box_autoadd_date_range(dynamic raw);

  @protected
  EbillConfig dco_decode_box_autoadd_ebill_config(dynamic raw);

  @protected
  EditCompanyPayload dco_decode_box_autoadd_edit_company_payload(dynamic raw);

  @protected
  EditContactPayload dco_decode_box_autoadd_edit_contact_payload(dynamic raw);

  @protected
  EndorseBitcreditBillPayload
  dco_decode_box_autoadd_endorse_bitcredit_bill_payload(dynamic raw);

  @protected
  FileFfi dco_decode_box_autoadd_file_ffi(dynamic raw);

  @protected
  GeneralSearchFilterPayload
  dco_decode_box_autoadd_general_search_filter_payload(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  IdentityEmailConfirmationFfi
  dco_decode_box_autoadd_identity_email_confirmation_ffi(dynamic raw);

  @protected
  InviteSignatoryPayload dco_decode_box_autoadd_invite_signatory_payload(
    dynamic raw,
  );

  @protected
  LightBillAnonParticipantFfi
  dco_decode_box_autoadd_light_bill_anon_participant_ffi(dynamic raw);

  @protected
  LightBillIdentParticipantWithAddressFfi
  dco_decode_box_autoadd_light_bill_ident_participant_with_address_ffi(
    dynamic raw,
  );

  @protected
  LightBillParticipantFfi dco_decode_box_autoadd_light_bill_participant_ffi(
    dynamic raw,
  );

  @protected
  LightBillSignatoryFfi dco_decode_box_autoadd_light_bill_signatory_ffi(
    dynamic raw,
  );

  @protected
  LocallyHideSignatoryPayload
  dco_decode_box_autoadd_locally_hide_signatory_payload(dynamic raw);

  @protected
  MintOfferFfi dco_decode_box_autoadd_mint_offer_ffi(dynamic raw);

  @protected
  NewContactPayload dco_decode_box_autoadd_new_contact_payload(dynamic raw);

  @protected
  NewIdentityPayload dco_decode_box_autoadd_new_identity_payload(dynamic raw);

  @protected
  NotificationFfi dco_decode_box_autoadd_notification_ffi(dynamic raw);

  @protected
  NotificationFiltersFfi dco_decode_box_autoadd_notification_filters_ffi(
    dynamic raw,
  );

  @protected
  OfferToSellBitcreditBillPayload
  dco_decode_box_autoadd_offer_to_sell_bitcredit_bill_payload(dynamic raw);

  @protected
  OptionalPostalAddressFfi dco_decode_box_autoadd_optional_postal_address_ffi(
    dynamic raw,
  );

  @protected
  PastPaymentDataPaymentFfi
  dco_decode_box_autoadd_past_payment_data_payment_ffi(dynamic raw);

  @protected
  PastPaymentDataRecourseFfi
  dco_decode_box_autoadd_past_payment_data_recourse_ffi(dynamic raw);

  @protected
  PastPaymentDataSellFfi dco_decode_box_autoadd_past_payment_data_sell_ffi(
    dynamic raw,
  );

  @protected
  PendingContactShareFfi dco_decode_box_autoadd_pending_contact_share_ffi(
    dynamic raw,
  );

  @protected
  PostalAddressFfi dco_decode_box_autoadd_postal_address_ffi(dynamic raw);

  @protected
  RejectActionBillPayload dco_decode_box_autoadd_reject_action_bill_payload(
    dynamic raw,
  );

  @protected
  RemoveSignatoryPayload dco_decode_box_autoadd_remove_signatory_payload(
    dynamic raw,
  );

  @protected
  RequestRecourseForAcceptancePayload
  dco_decode_box_autoadd_request_recourse_for_acceptance_payload(dynamic raw);

  @protected
  RequestRecourseForPaymentPayload
  dco_decode_box_autoadd_request_recourse_for_payment_payload(dynamic raw);

  @protected
  RequestToAcceptBitcreditBillPayload
  dco_decode_box_autoadd_request_to_accept_bitcredit_bill_payload(dynamic raw);

  @protected
  RequestToMintBitcreditBillPayload
  dco_decode_box_autoadd_request_to_mint_bitcredit_bill_payload(dynamic raw);

  @protected
  RequestToPayAsMintBitcreditBillPayload
  dco_decode_box_autoadd_request_to_pay_as_mint_bitcredit_bill_payload(
    dynamic raw,
  );

  @protected
  RequestToPayBitcreditBillPayload
  dco_decode_box_autoadd_request_to_pay_bitcredit_bill_payload(dynamic raw);

  @protected
  ResyncBillPayload dco_decode_box_autoadd_resync_bill_payload(dynamic raw);

  @protected
  ResyncCompanyPayload dco_decode_box_autoadd_resync_company_payload(
    dynamic raw,
  );

  @protected
  SearchContactsPayload dco_decode_box_autoadd_search_contacts_payload(
    dynamic raw,
  );

  @protected
  SeedPhrase dco_decode_box_autoadd_seed_phrase(dynamic raw);

  @protected
  ShareBillWithCourtPayload
  dco_decode_box_autoadd_share_bill_with_court_payload(dynamic raw);

  @protected
  ShareCompanyContactTo dco_decode_box_autoadd_share_company_contact_to(
    dynamic raw,
  );

  @protected
  ShareContactTo dco_decode_box_autoadd_share_contact_to(dynamic raw);

  @protected
  SwitchIdentity dco_decode_box_autoadd_switch_identity(dynamic raw);

  @protected
  SwitchIdentityTypeFfi dco_decode_box_autoadd_switch_identity_type_ffi(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  UploadFile dco_decode_box_autoadd_upload_file(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  VerifyEmailPayload dco_decode_box_autoadd_verify_email_payload(dynamic raw);

  @protected
  BtcAddressAndSumPayload dco_decode_btc_address_and_sum_payload(dynamic raw);

  @protected
  BtcAddressPayload dco_decode_btc_address_payload(dynamic raw);

  @protected
  ChangeIdentityEmailPayload dco_decode_change_identity_email_payload(
    dynamic raw,
  );

  @protected
  ChangeIdentityPayload dco_decode_change_identity_payload(dynamic raw);

  @protected
  ChangeSignatoryEmailPayload dco_decode_change_signatory_email_payload(
    dynamic raw,
  );

  @protected
  CompaniesResponse dco_decode_companies_response(dynamic raw);

  @protected
  CompanyConfirmEmailPayload dco_decode_company_confirm_email_payload(
    dynamic raw,
  );

  @protected
  CompanyFfi dco_decode_company_ffi(dynamic raw);

  @protected
  CompanyKeysFfi dco_decode_company_keys_ffi(dynamic raw);

  @protected
  CompanySignatoryFfi dco_decode_company_signatory_ffi(dynamic raw);

  @protected
  CompanySignatoryStatusFfi dco_decode_company_signatory_status_ffi(
    dynamic raw,
  );

  @protected
  CompanyStatusFfi dco_decode_company_status_ffi(dynamic raw);

  @protected
  CompanyVerifyEmailPayload dco_decode_company_verify_email_payload(
    dynamic raw,
  );

  @protected
  ConfirmEmailPayload dco_decode_confirm_email_payload(dynamic raw);

  @protected
  ContactFfi dco_decode_contact_ffi(dynamic raw);

  @protected
  ContactTypeFfi dco_decode_contact_type_ffi(dynamic raw);

  @protected
  ContactsResponse dco_decode_contacts_response(dynamic raw);

  @protected
  CreateCompanyPayload dco_decode_create_company_payload(dynamic raw);

  @protected
  CreateOptionalPostalAddressFfi dco_decode_create_optional_postal_address_ffi(
    dynamic raw,
  );

  @protected
  CreatePostalAddressFfi dco_decode_create_postal_address_ffi(dynamic raw);

  @protected
  CurrenciesResponse dco_decode_currencies_response(dynamic raw);

  @protected
  CurrencyResponse dco_decode_currency_response(dynamic raw);

  @protected
  DateRange dco_decode_date_range(dynamic raw);

  @protected
  EbillConfig dco_decode_ebill_config(dynamic raw);

  @protected
  EbillFfiError dco_decode_ebill_ffi_error(dynamic raw);

  @protected
  EbillFfiErrorCode dco_decode_ebill_ffi_error_code(dynamic raw);

  @protected
  EbillFfiErrorKind dco_decode_ebill_ffi_error_kind(dynamic raw);

  @protected
  EditCompanyPayload dco_decode_edit_company_payload(dynamic raw);

  @protected
  EditContactPayload dco_decode_edit_contact_payload(dynamic raw);

  @protected
  EditOptionalFieldModeFfi dco_decode_edit_optional_field_mode_ffi(dynamic raw);

  @protected
  EndorseBitcreditBillPayload dco_decode_endorse_bitcredit_bill_payload(
    dynamic raw,
  );

  @protected
  EndorsementFfi dco_decode_endorsement_ffi(dynamic raw);

  @protected
  EndorsementsResponse dco_decode_endorsements_response(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FileFfi dco_decode_file_ffi(dynamic raw);

  @protected
  GeneralSearchFilter dco_decode_general_search_filter(dynamic raw);

  @protected
  GeneralSearchFilterItemTypeFfi dco_decode_general_search_filter_item_type_ffi(
    dynamic raw,
  );

  @protected
  GeneralSearchFilterPayload dco_decode_general_search_filter_payload(
    dynamic raw,
  );

  @protected
  GeneralSearchResponse dco_decode_general_search_response(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IdentityEmailConfirmationFfi dco_decode_identity_email_confirmation_ffi(
    dynamic raw,
  );

  @protected
  IdentityFfi dco_decode_identity_ffi(dynamic raw);

  @protected
  IdentityTypeFfi dco_decode_identity_type_ffi(dynamic raw);

  @protected
  InviteSignatoryPayload dco_decode_invite_signatory_payload(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  LightBillAnonParticipantFfi dco_decode_light_bill_anon_participant_ffi(
    dynamic raw,
  );

  @protected
  LightBillIdentParticipantFfi dco_decode_light_bill_ident_participant_ffi(
    dynamic raw,
  );

  @protected
  LightBillIdentParticipantWithAddressFfi
  dco_decode_light_bill_ident_participant_with_address_ffi(dynamic raw);

  @protected
  LightBillParticipantFfi dco_decode_light_bill_participant_ffi(dynamic raw);

  @protected
  LightBillSignatoryFfi dco_decode_light_bill_signatory_ffi(dynamic raw);

  @protected
  LightBillsResponse dco_decode_light_bills_response(dynamic raw);

  @protected
  LightBitcreditBillFfi dco_decode_light_bitcredit_bill_ffi(dynamic raw);

  @protected
  LightSignedByFfi dco_decode_light_signed_by_ffi(dynamic raw);

  @protected
  LinkToPayResponse dco_decode_link_to_pay_response(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BillCallerBillActionFfi> dco_decode_list_bill_caller_bill_action_ffi(
    dynamic raw,
  );

  @protected
  List<BillCallerPaymentActionFfi>
  dco_decode_list_bill_caller_payment_action_ffi(dynamic raw);

  @protected
  List<BillCombinedBitcoinKeyFfi> dco_decode_list_bill_combined_bitcoin_key_ffi(
    dynamic raw,
  );

  @protected
  List<BillHistoryBlockFfi> dco_decode_list_bill_history_block_ffi(dynamic raw);

  @protected
  List<BitcreditBillFfi> dco_decode_list_bitcredit_bill_ffi(dynamic raw);

  @protected
  List<CompanyFfi> dco_decode_list_company_ffi(dynamic raw);

  @protected
  List<CompanySignatoryFfi> dco_decode_list_company_signatory_ffi(dynamic raw);

  @protected
  List<ContactFfi> dco_decode_list_contact_ffi(dynamic raw);

  @protected
  List<CurrencyResponse> dco_decode_list_currency_response(dynamic raw);

  @protected
  List<EndorsementFfi> dco_decode_list_endorsement_ffi(dynamic raw);

  @protected
  List<FileFfi> dco_decode_list_file_ffi(dynamic raw);

  @protected
  List<GeneralSearchFilterItemTypeFfi>
  dco_decode_list_general_search_filter_item_type_ffi(dynamic raw);

  @protected
  List<IdentityEmailConfirmationFfi>
  dco_decode_list_identity_email_confirmation_ffi(dynamic raw);

  @protected
  List<LightBitcreditBillFfi> dco_decode_list_light_bitcredit_bill_ffi(
    dynamic raw,
  );

  @protected
  List<MintRequestStateFfi> dco_decode_list_mint_request_state_ffi(dynamic raw);

  @protected
  List<NotificationFfi> dco_decode_list_notification_ffi(dynamic raw);

  @protected
  List<NotificationStatusFfi> dco_decode_list_notification_status_ffi(
    dynamic raw,
  );

  @protected
  List<PastEndorseeFfi> dco_decode_list_past_endorsee_ffi(dynamic raw);

  @protected
  List<PastPaymentResultFfi> dco_decode_list_past_payment_result_ffi(
    dynamic raw,
  );

  @protected
  List<PendingContactShareFfi> dco_decode_list_pending_contact_share_ffi(
    dynamic raw,
  );

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  ListSignatoriesResponse dco_decode_list_signatories_response(dynamic raw);

  @protected
  List<SignatoryResponse> dco_decode_list_signatory_response(dynamic raw);

  @protected
  LocallyHideSignatoryPayload dco_decode_locally_hide_signatory_payload(
    dynamic raw,
  );

  @protected
  MempoolLinkResponse dco_decode_mempool_link_response(dynamic raw);

  @protected
  MintOfferFfi dco_decode_mint_offer_ffi(dynamic raw);

  @protected
  MintRequestFfi dco_decode_mint_request_ffi(dynamic raw);

  @protected
  MintRequestStateFfi dco_decode_mint_request_state_ffi(dynamic raw);

  @protected
  MintRequestStateResponse dco_decode_mint_request_state_response(dynamic raw);

  @protected
  MintRequestStatusFfi dco_decode_mint_request_status_ffi(dynamic raw);

  @protected
  NewContactPayload dco_decode_new_contact_payload(dynamic raw);

  @protected
  NewIdentityPayload dco_decode_new_identity_payload(dynamic raw);

  @protected
  NotificationFfi dco_decode_notification_ffi(dynamic raw);

  @protected
  NotificationFiltersFfi dco_decode_notification_filters_ffi(dynamic raw);

  @protected
  NotificationLevelFfi dco_decode_notification_level_ffi(dynamic raw);

  @protected
  NotificationStatusFfi dco_decode_notification_status_ffi(dynamic raw);

  @protected
  NotificationSubscriptionResponse
  dco_decode_notification_subscription_response(dynamic raw);

  @protected
  NotificationTypeFfi dco_decode_notification_type_ffi(dynamic raw);

  @protected
  OfferToSellBitcreditBillPayload
  dco_decode_offer_to_sell_bitcredit_bill_payload(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BillCurrentWaitingStateFfi?
  dco_decode_opt_box_autoadd_bill_current_waiting_state_ffi(dynamic raw);

  @protected
  BillHistoryBlockPaymentDataFfi?
  dco_decode_opt_box_autoadd_bill_history_block_payment_data_ffi(dynamic raw);

  @protected
  BillParticipantFfi? dco_decode_opt_box_autoadd_bill_participant_ffi(
    dynamic raw,
  );

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  CreatePostalAddressFfi? dco_decode_opt_box_autoadd_create_postal_address_ffi(
    dynamic raw,
  );

  @protected
  DateRange? dco_decode_opt_box_autoadd_date_range(dynamic raw);

  @protected
  FileFfi? dco_decode_opt_box_autoadd_file_ffi(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  LightBillParticipantFfi?
  dco_decode_opt_box_autoadd_light_bill_participant_ffi(dynamic raw);

  @protected
  LightBillSignatoryFfi? dco_decode_opt_box_autoadd_light_bill_signatory_ffi(
    dynamic raw,
  );

  @protected
  MintOfferFfi? dco_decode_opt_box_autoadd_mint_offer_ffi(dynamic raw);

  @protected
  NotificationFfi? dco_decode_opt_box_autoadd_notification_ffi(dynamic raw);

  @protected
  PendingContactShareFfi? dco_decode_opt_box_autoadd_pending_contact_share_ffi(
    dynamic raw,
  );

  @protected
  PostalAddressFfi? dco_decode_opt_box_autoadd_postal_address_ffi(dynamic raw);

  @protected
  SwitchIdentityTypeFfi? dco_decode_opt_box_autoadd_switch_identity_type_ffi(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  OptionalPostalAddressFfi dco_decode_optional_postal_address_ffi(dynamic raw);

  @protected
  OverviewBalanceResponse dco_decode_overview_balance_response(dynamic raw);

  @protected
  OverviewResponse dco_decode_overview_response(dynamic raw);

  @protected
  PastEndorseeFfi dco_decode_past_endorsee_ffi(dynamic raw);

  @protected
  PastEndorseesResponse dco_decode_past_endorsees_response(dynamic raw);

  @protected
  PastPaymentDataPaymentFfi dco_decode_past_payment_data_payment_ffi(
    dynamic raw,
  );

  @protected
  PastPaymentDataRecourseFfi dco_decode_past_payment_data_recourse_ffi(
    dynamic raw,
  );

  @protected
  PastPaymentDataSellFfi dco_decode_past_payment_data_sell_ffi(dynamic raw);

  @protected
  PastPaymentResultFfi dco_decode_past_payment_result_ffi(dynamic raw);

  @protected
  PastPaymentsResponse dco_decode_past_payments_response(dynamic raw);

  @protected
  PaymentStatusFfi dco_decode_payment_status_ffi(dynamic raw);

  @protected
  PendingContactShareFfi dco_decode_pending_contact_share_ffi(dynamic raw);

  @protected
  PendingContactSharesResponse dco_decode_pending_contact_shares_response(
    dynamic raw,
  );

  @protected
  PostalAddressFfi dco_decode_postal_address_ffi(dynamic raw);

  @protected
  RejectActionBillPayload dco_decode_reject_action_bill_payload(dynamic raw);

  @protected
  RemoveSignatoryPayload dco_decode_remove_signatory_payload(dynamic raw);

  @protected
  RequestRecourseForAcceptancePayload
  dco_decode_request_recourse_for_acceptance_payload(dynamic raw);

  @protected
  RequestRecourseForPaymentPayload
  dco_decode_request_recourse_for_payment_payload(dynamic raw);

  @protected
  RequestToAcceptBitcreditBillPayload
  dco_decode_request_to_accept_bitcredit_bill_payload(dynamic raw);

  @protected
  RequestToMintBitcreditBillPayload
  dco_decode_request_to_mint_bitcredit_bill_payload(dynamic raw);

  @protected
  RequestToPayAsMintBitcreditBillPayload
  dco_decode_request_to_pay_as_mint_bitcredit_bill_payload(dynamic raw);

  @protected
  RequestToPayBitcreditBillPayload
  dco_decode_request_to_pay_bitcredit_bill_payload(dynamic raw);

  @protected
  ResyncBillPayload dco_decode_resync_bill_payload(dynamic raw);

  @protected
  ResyncCompanyPayload dco_decode_resync_company_payload(dynamic raw);

  @protected
  SearchContactsPayload dco_decode_search_contacts_payload(dynamic raw);

  @protected
  SeedPhrase dco_decode_seed_phrase(dynamic raw);

  @protected
  ShareBillWithCourtPayload dco_decode_share_bill_with_court_payload(
    dynamic raw,
  );

  @protected
  ShareCompanyContactTo dco_decode_share_company_contact_to(dynamic raw);

  @protected
  ShareContactTo dco_decode_share_contact_to(dynamic raw);

  @protected
  SignatoryResponse dco_decode_signatory_response(dynamic raw);

  @protected
  StatusResponse dco_decode_status_response(dynamic raw);

  @protected
  SwitchIdentity dco_decode_switch_identity(dynamic raw);

  @protected
  SwitchIdentityTypeFfi dco_decode_switch_identity_type_ffi(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UploadFile dco_decode_upload_file(dynamic raw);

  @protected
  UploadFileResponse dco_decode_upload_file_response(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VerifyEmailPayload dco_decode_verify_email_payload(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AcceptBitcreditBillPayload sse_decode_accept_bitcredit_bill_payload(
    SseDeserializer deserializer,
  );

  @protected
  AcceptCompanyInvitePayload sse_decode_accept_company_invite_payload(
    SseDeserializer deserializer,
  );

  @protected
  ApproveContactSharePayload sse_decode_approve_contact_share_payload(
    SseDeserializer deserializer,
  );

  @protected
  BalanceResponse sse_decode_balance_response(SseDeserializer deserializer);

  @protected
  Base64FileResponse sse_decode_base_64_file_response(
    SseDeserializer deserializer,
  );

  @protected
  BillAcceptStateFfi sse_decode_bill_accept_state_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillAcceptanceStatusFfi sse_decode_bill_acceptance_status_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillAnonParticipantFfi sse_decode_bill_anon_participant_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillCallerActionsFfi sse_decode_bill_caller_actions_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillCallerBillActionFfi sse_decode_bill_caller_bill_action_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillCallerPaymentActionFfi sse_decode_bill_caller_payment_action_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillCallerPaymentFfi sse_decode_bill_caller_payment_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillCallerPaymentStateFfi sse_decode_bill_caller_payment_state_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillCheckSweepBTCFundsPayload sse_decode_bill_check_sweep_btc_funds_payload(
    SseDeserializer deserializer,
  );

  @protected
  BillCombinedBitcoinKeyFfi sse_decode_bill_combined_bitcoin_key_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillCurrentWaitingStateFfi sse_decode_bill_current_waiting_state_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillDataFfi sse_decode_bill_data_ffi(SseDeserializer deserializer);

  @protected
  BillHistoryBlockFfi sse_decode_bill_history_block_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillHistoryBlockPaymentDataFfi sse_decode_bill_history_block_payment_data_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillHistoryResponse sse_decode_bill_history_response(
    SseDeserializer deserializer,
  );

  @protected
  BillIdResponse sse_decode_bill_id_response(SseDeserializer deserializer);

  @protected
  BillIdentParticipantFfi sse_decode_bill_ident_participant_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillMintStateFfi sse_decode_bill_mint_state_ffi(SseDeserializer deserializer);

  @protected
  BillMintStatusFfi sse_decode_bill_mint_status_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillOpCodeFfi sse_decode_bill_op_code_ffi(SseDeserializer deserializer);

  @protected
  BillParticipantFfi sse_decode_bill_participant_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillParticipantsFfi sse_decode_bill_participants_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillPaymentStateFfi sse_decode_bill_payment_state_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillPaymentStatusFfi sse_decode_bill_payment_status_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillRecourseStatusFfi sse_decode_bill_recourse_status_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillSellStatusFfi sse_decode_bill_sell_status_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillStateFfi sse_decode_bill_state_ffi(SseDeserializer deserializer);

  @protected
  BillStatusFfi sse_decode_bill_status_ffi(SseDeserializer deserializer);

  @protected
  BillSweepBTCEstimateFfi sse_decode_bill_sweep_btc_estimate_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillSweepBTCFundsPayload sse_decode_bill_sweep_btc_funds_payload(
    SseDeserializer deserializer,
  );

  @protected
  BillSweepBTCFundsResultFfi sse_decode_bill_sweep_btc_funds_result_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillSweepBTCOptionFfi sse_decode_bill_sweep_btc_option_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillWaitingForPaymentStateFfi sse_decode_bill_waiting_for_payment_state_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillWaitingForRecourseStateFfi sse_decode_bill_waiting_for_recourse_state_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillWaitingForSellStateFfi sse_decode_bill_waiting_for_sell_state_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillWaitingStatePaymentDataFfi sse_decode_bill_waiting_state_payment_data_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillsFilterRoleFfi sse_decode_bills_filter_role_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillsResponse sse_decode_bills_response(SseDeserializer deserializer);

  @protected
  BillsSearchFilter sse_decode_bills_search_filter(
    SseDeserializer deserializer,
  );

  @protected
  BillsSearchFilterPayload sse_decode_bills_search_filter_payload(
    SseDeserializer deserializer,
  );

  @protected
  BinaryFileResponse sse_decode_binary_file_response(
    SseDeserializer deserializer,
  );

  @protected
  BitcreditBillFfi sse_decode_bitcredit_bill_ffi(SseDeserializer deserializer);

  @protected
  BitcreditBillPayload sse_decode_bitcredit_bill_payload(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AcceptBitcreditBillPayload
  sse_decode_box_autoadd_accept_bitcredit_bill_payload(
    SseDeserializer deserializer,
  );

  @protected
  AcceptCompanyInvitePayload
  sse_decode_box_autoadd_accept_company_invite_payload(
    SseDeserializer deserializer,
  );

  @protected
  ApproveContactSharePayload
  sse_decode_box_autoadd_approve_contact_share_payload(
    SseDeserializer deserializer,
  );

  @protected
  BillAnonParticipantFfi sse_decode_box_autoadd_bill_anon_participant_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillCallerPaymentFfi sse_decode_box_autoadd_bill_caller_payment_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillCallerPaymentStateFfi
  sse_decode_box_autoadd_bill_caller_payment_state_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillCheckSweepBTCFundsPayload
  sse_decode_box_autoadd_bill_check_sweep_btc_funds_payload(
    SseDeserializer deserializer,
  );

  @protected
  BillCurrentWaitingStateFfi
  sse_decode_box_autoadd_bill_current_waiting_state_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillHistoryBlockPaymentDataFfi
  sse_decode_box_autoadd_bill_history_block_payment_data_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillIdentParticipantFfi sse_decode_box_autoadd_bill_ident_participant_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillParticipantFfi sse_decode_box_autoadd_bill_participant_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillSweepBTCFundsPayload sse_decode_box_autoadd_bill_sweep_btc_funds_payload(
    SseDeserializer deserializer,
  );

  @protected
  BillWaitingForPaymentStateFfi
  sse_decode_box_autoadd_bill_waiting_for_payment_state_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillWaitingForRecourseStateFfi
  sse_decode_box_autoadd_bill_waiting_for_recourse_state_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillWaitingForSellStateFfi
  sse_decode_box_autoadd_bill_waiting_for_sell_state_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillsSearchFilterPayload sse_decode_box_autoadd_bills_search_filter_payload(
    SseDeserializer deserializer,
  );

  @protected
  BitcreditBillPayload sse_decode_box_autoadd_bitcredit_bill_payload(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  BtcAddressAndSumPayload sse_decode_box_autoadd_btc_address_and_sum_payload(
    SseDeserializer deserializer,
  );

  @protected
  BtcAddressPayload sse_decode_box_autoadd_btc_address_payload(
    SseDeserializer deserializer,
  );

  @protected
  ChangeIdentityEmailPayload
  sse_decode_box_autoadd_change_identity_email_payload(
    SseDeserializer deserializer,
  );

  @protected
  ChangeIdentityPayload sse_decode_box_autoadd_change_identity_payload(
    SseDeserializer deserializer,
  );

  @protected
  ChangeSignatoryEmailPayload
  sse_decode_box_autoadd_change_signatory_email_payload(
    SseDeserializer deserializer,
  );

  @protected
  CompanyConfirmEmailPayload
  sse_decode_box_autoadd_company_confirm_email_payload(
    SseDeserializer deserializer,
  );

  @protected
  CompanyVerifyEmailPayload sse_decode_box_autoadd_company_verify_email_payload(
    SseDeserializer deserializer,
  );

  @protected
  ConfirmEmailPayload sse_decode_box_autoadd_confirm_email_payload(
    SseDeserializer deserializer,
  );

  @protected
  CreateCompanyPayload sse_decode_box_autoadd_create_company_payload(
    SseDeserializer deserializer,
  );

  @protected
  CreateOptionalPostalAddressFfi
  sse_decode_box_autoadd_create_optional_postal_address_ffi(
    SseDeserializer deserializer,
  );

  @protected
  CreatePostalAddressFfi sse_decode_box_autoadd_create_postal_address_ffi(
    SseDeserializer deserializer,
  );

  @protected
  DateRange sse_decode_box_autoadd_date_range(SseDeserializer deserializer);

  @protected
  EbillConfig sse_decode_box_autoadd_ebill_config(SseDeserializer deserializer);

  @protected
  EditCompanyPayload sse_decode_box_autoadd_edit_company_payload(
    SseDeserializer deserializer,
  );

  @protected
  EditContactPayload sse_decode_box_autoadd_edit_contact_payload(
    SseDeserializer deserializer,
  );

  @protected
  EndorseBitcreditBillPayload
  sse_decode_box_autoadd_endorse_bitcredit_bill_payload(
    SseDeserializer deserializer,
  );

  @protected
  FileFfi sse_decode_box_autoadd_file_ffi(SseDeserializer deserializer);

  @protected
  GeneralSearchFilterPayload
  sse_decode_box_autoadd_general_search_filter_payload(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  IdentityEmailConfirmationFfi
  sse_decode_box_autoadd_identity_email_confirmation_ffi(
    SseDeserializer deserializer,
  );

  @protected
  InviteSignatoryPayload sse_decode_box_autoadd_invite_signatory_payload(
    SseDeserializer deserializer,
  );

  @protected
  LightBillAnonParticipantFfi
  sse_decode_box_autoadd_light_bill_anon_participant_ffi(
    SseDeserializer deserializer,
  );

  @protected
  LightBillIdentParticipantWithAddressFfi
  sse_decode_box_autoadd_light_bill_ident_participant_with_address_ffi(
    SseDeserializer deserializer,
  );

  @protected
  LightBillParticipantFfi sse_decode_box_autoadd_light_bill_participant_ffi(
    SseDeserializer deserializer,
  );

  @protected
  LightBillSignatoryFfi sse_decode_box_autoadd_light_bill_signatory_ffi(
    SseDeserializer deserializer,
  );

  @protected
  LocallyHideSignatoryPayload
  sse_decode_box_autoadd_locally_hide_signatory_payload(
    SseDeserializer deserializer,
  );

  @protected
  MintOfferFfi sse_decode_box_autoadd_mint_offer_ffi(
    SseDeserializer deserializer,
  );

  @protected
  NewContactPayload sse_decode_box_autoadd_new_contact_payload(
    SseDeserializer deserializer,
  );

  @protected
  NewIdentityPayload sse_decode_box_autoadd_new_identity_payload(
    SseDeserializer deserializer,
  );

  @protected
  NotificationFfi sse_decode_box_autoadd_notification_ffi(
    SseDeserializer deserializer,
  );

  @protected
  NotificationFiltersFfi sse_decode_box_autoadd_notification_filters_ffi(
    SseDeserializer deserializer,
  );

  @protected
  OfferToSellBitcreditBillPayload
  sse_decode_box_autoadd_offer_to_sell_bitcredit_bill_payload(
    SseDeserializer deserializer,
  );

  @protected
  OptionalPostalAddressFfi sse_decode_box_autoadd_optional_postal_address_ffi(
    SseDeserializer deserializer,
  );

  @protected
  PastPaymentDataPaymentFfi
  sse_decode_box_autoadd_past_payment_data_payment_ffi(
    SseDeserializer deserializer,
  );

  @protected
  PastPaymentDataRecourseFfi
  sse_decode_box_autoadd_past_payment_data_recourse_ffi(
    SseDeserializer deserializer,
  );

  @protected
  PastPaymentDataSellFfi sse_decode_box_autoadd_past_payment_data_sell_ffi(
    SseDeserializer deserializer,
  );

  @protected
  PendingContactShareFfi sse_decode_box_autoadd_pending_contact_share_ffi(
    SseDeserializer deserializer,
  );

  @protected
  PostalAddressFfi sse_decode_box_autoadd_postal_address_ffi(
    SseDeserializer deserializer,
  );

  @protected
  RejectActionBillPayload sse_decode_box_autoadd_reject_action_bill_payload(
    SseDeserializer deserializer,
  );

  @protected
  RemoveSignatoryPayload sse_decode_box_autoadd_remove_signatory_payload(
    SseDeserializer deserializer,
  );

  @protected
  RequestRecourseForAcceptancePayload
  sse_decode_box_autoadd_request_recourse_for_acceptance_payload(
    SseDeserializer deserializer,
  );

  @protected
  RequestRecourseForPaymentPayload
  sse_decode_box_autoadd_request_recourse_for_payment_payload(
    SseDeserializer deserializer,
  );

  @protected
  RequestToAcceptBitcreditBillPayload
  sse_decode_box_autoadd_request_to_accept_bitcredit_bill_payload(
    SseDeserializer deserializer,
  );

  @protected
  RequestToMintBitcreditBillPayload
  sse_decode_box_autoadd_request_to_mint_bitcredit_bill_payload(
    SseDeserializer deserializer,
  );

  @protected
  RequestToPayAsMintBitcreditBillPayload
  sse_decode_box_autoadd_request_to_pay_as_mint_bitcredit_bill_payload(
    SseDeserializer deserializer,
  );

  @protected
  RequestToPayBitcreditBillPayload
  sse_decode_box_autoadd_request_to_pay_bitcredit_bill_payload(
    SseDeserializer deserializer,
  );

  @protected
  ResyncBillPayload sse_decode_box_autoadd_resync_bill_payload(
    SseDeserializer deserializer,
  );

  @protected
  ResyncCompanyPayload sse_decode_box_autoadd_resync_company_payload(
    SseDeserializer deserializer,
  );

  @protected
  SearchContactsPayload sse_decode_box_autoadd_search_contacts_payload(
    SseDeserializer deserializer,
  );

  @protected
  SeedPhrase sse_decode_box_autoadd_seed_phrase(SseDeserializer deserializer);

  @protected
  ShareBillWithCourtPayload
  sse_decode_box_autoadd_share_bill_with_court_payload(
    SseDeserializer deserializer,
  );

  @protected
  ShareCompanyContactTo sse_decode_box_autoadd_share_company_contact_to(
    SseDeserializer deserializer,
  );

  @protected
  ShareContactTo sse_decode_box_autoadd_share_contact_to(
    SseDeserializer deserializer,
  );

  @protected
  SwitchIdentity sse_decode_box_autoadd_switch_identity(
    SseDeserializer deserializer,
  );

  @protected
  SwitchIdentityTypeFfi sse_decode_box_autoadd_switch_identity_type_ffi(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  UploadFile sse_decode_box_autoadd_upload_file(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  VerifyEmailPayload sse_decode_box_autoadd_verify_email_payload(
    SseDeserializer deserializer,
  );

  @protected
  BtcAddressAndSumPayload sse_decode_btc_address_and_sum_payload(
    SseDeserializer deserializer,
  );

  @protected
  BtcAddressPayload sse_decode_btc_address_payload(
    SseDeserializer deserializer,
  );

  @protected
  ChangeIdentityEmailPayload sse_decode_change_identity_email_payload(
    SseDeserializer deserializer,
  );

  @protected
  ChangeIdentityPayload sse_decode_change_identity_payload(
    SseDeserializer deserializer,
  );

  @protected
  ChangeSignatoryEmailPayload sse_decode_change_signatory_email_payload(
    SseDeserializer deserializer,
  );

  @protected
  CompaniesResponse sse_decode_companies_response(SseDeserializer deserializer);

  @protected
  CompanyConfirmEmailPayload sse_decode_company_confirm_email_payload(
    SseDeserializer deserializer,
  );

  @protected
  CompanyFfi sse_decode_company_ffi(SseDeserializer deserializer);

  @protected
  CompanyKeysFfi sse_decode_company_keys_ffi(SseDeserializer deserializer);

  @protected
  CompanySignatoryFfi sse_decode_company_signatory_ffi(
    SseDeserializer deserializer,
  );

  @protected
  CompanySignatoryStatusFfi sse_decode_company_signatory_status_ffi(
    SseDeserializer deserializer,
  );

  @protected
  CompanyStatusFfi sse_decode_company_status_ffi(SseDeserializer deserializer);

  @protected
  CompanyVerifyEmailPayload sse_decode_company_verify_email_payload(
    SseDeserializer deserializer,
  );

  @protected
  ConfirmEmailPayload sse_decode_confirm_email_payload(
    SseDeserializer deserializer,
  );

  @protected
  ContactFfi sse_decode_contact_ffi(SseDeserializer deserializer);

  @protected
  ContactTypeFfi sse_decode_contact_type_ffi(SseDeserializer deserializer);

  @protected
  ContactsResponse sse_decode_contacts_response(SseDeserializer deserializer);

  @protected
  CreateCompanyPayload sse_decode_create_company_payload(
    SseDeserializer deserializer,
  );

  @protected
  CreateOptionalPostalAddressFfi sse_decode_create_optional_postal_address_ffi(
    SseDeserializer deserializer,
  );

  @protected
  CreatePostalAddressFfi sse_decode_create_postal_address_ffi(
    SseDeserializer deserializer,
  );

  @protected
  CurrenciesResponse sse_decode_currencies_response(
    SseDeserializer deserializer,
  );

  @protected
  CurrencyResponse sse_decode_currency_response(SseDeserializer deserializer);

  @protected
  DateRange sse_decode_date_range(SseDeserializer deserializer);

  @protected
  EbillConfig sse_decode_ebill_config(SseDeserializer deserializer);

  @protected
  EbillFfiError sse_decode_ebill_ffi_error(SseDeserializer deserializer);

  @protected
  EbillFfiErrorCode sse_decode_ebill_ffi_error_code(
    SseDeserializer deserializer,
  );

  @protected
  EbillFfiErrorKind sse_decode_ebill_ffi_error_kind(
    SseDeserializer deserializer,
  );

  @protected
  EditCompanyPayload sse_decode_edit_company_payload(
    SseDeserializer deserializer,
  );

  @protected
  EditContactPayload sse_decode_edit_contact_payload(
    SseDeserializer deserializer,
  );

  @protected
  EditOptionalFieldModeFfi sse_decode_edit_optional_field_mode_ffi(
    SseDeserializer deserializer,
  );

  @protected
  EndorseBitcreditBillPayload sse_decode_endorse_bitcredit_bill_payload(
    SseDeserializer deserializer,
  );

  @protected
  EndorsementFfi sse_decode_endorsement_ffi(SseDeserializer deserializer);

  @protected
  EndorsementsResponse sse_decode_endorsements_response(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FileFfi sse_decode_file_ffi(SseDeserializer deserializer);

  @protected
  GeneralSearchFilter sse_decode_general_search_filter(
    SseDeserializer deserializer,
  );

  @protected
  GeneralSearchFilterItemTypeFfi sse_decode_general_search_filter_item_type_ffi(
    SseDeserializer deserializer,
  );

  @protected
  GeneralSearchFilterPayload sse_decode_general_search_filter_payload(
    SseDeserializer deserializer,
  );

  @protected
  GeneralSearchResponse sse_decode_general_search_response(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IdentityEmailConfirmationFfi sse_decode_identity_email_confirmation_ffi(
    SseDeserializer deserializer,
  );

  @protected
  IdentityFfi sse_decode_identity_ffi(SseDeserializer deserializer);

  @protected
  IdentityTypeFfi sse_decode_identity_type_ffi(SseDeserializer deserializer);

  @protected
  InviteSignatoryPayload sse_decode_invite_signatory_payload(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  LightBillAnonParticipantFfi sse_decode_light_bill_anon_participant_ffi(
    SseDeserializer deserializer,
  );

  @protected
  LightBillIdentParticipantFfi sse_decode_light_bill_ident_participant_ffi(
    SseDeserializer deserializer,
  );

  @protected
  LightBillIdentParticipantWithAddressFfi
  sse_decode_light_bill_ident_participant_with_address_ffi(
    SseDeserializer deserializer,
  );

  @protected
  LightBillParticipantFfi sse_decode_light_bill_participant_ffi(
    SseDeserializer deserializer,
  );

  @protected
  LightBillSignatoryFfi sse_decode_light_bill_signatory_ffi(
    SseDeserializer deserializer,
  );

  @protected
  LightBillsResponse sse_decode_light_bills_response(
    SseDeserializer deserializer,
  );

  @protected
  LightBitcreditBillFfi sse_decode_light_bitcredit_bill_ffi(
    SseDeserializer deserializer,
  );

  @protected
  LightSignedByFfi sse_decode_light_signed_by_ffi(SseDeserializer deserializer);

  @protected
  LinkToPayResponse sse_decode_link_to_pay_response(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BillCallerBillActionFfi> sse_decode_list_bill_caller_bill_action_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<BillCallerPaymentActionFfi>
  sse_decode_list_bill_caller_payment_action_ffi(SseDeserializer deserializer);

  @protected
  List<BillCombinedBitcoinKeyFfi> sse_decode_list_bill_combined_bitcoin_key_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<BillHistoryBlockFfi> sse_decode_list_bill_history_block_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<BitcreditBillFfi> sse_decode_list_bitcredit_bill_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<CompanyFfi> sse_decode_list_company_ffi(SseDeserializer deserializer);

  @protected
  List<CompanySignatoryFfi> sse_decode_list_company_signatory_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<ContactFfi> sse_decode_list_contact_ffi(SseDeserializer deserializer);

  @protected
  List<CurrencyResponse> sse_decode_list_currency_response(
    SseDeserializer deserializer,
  );

  @protected
  List<EndorsementFfi> sse_decode_list_endorsement_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<FileFfi> sse_decode_list_file_ffi(SseDeserializer deserializer);

  @protected
  List<GeneralSearchFilterItemTypeFfi>
  sse_decode_list_general_search_filter_item_type_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<IdentityEmailConfirmationFfi>
  sse_decode_list_identity_email_confirmation_ffi(SseDeserializer deserializer);

  @protected
  List<LightBitcreditBillFfi> sse_decode_list_light_bitcredit_bill_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<MintRequestStateFfi> sse_decode_list_mint_request_state_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<NotificationFfi> sse_decode_list_notification_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<NotificationStatusFfi> sse_decode_list_notification_status_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<PastEndorseeFfi> sse_decode_list_past_endorsee_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<PastPaymentResultFfi> sse_decode_list_past_payment_result_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<PendingContactShareFfi> sse_decode_list_pending_contact_share_ffi(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  ListSignatoriesResponse sse_decode_list_signatories_response(
    SseDeserializer deserializer,
  );

  @protected
  List<SignatoryResponse> sse_decode_list_signatory_response(
    SseDeserializer deserializer,
  );

  @protected
  LocallyHideSignatoryPayload sse_decode_locally_hide_signatory_payload(
    SseDeserializer deserializer,
  );

  @protected
  MempoolLinkResponse sse_decode_mempool_link_response(
    SseDeserializer deserializer,
  );

  @protected
  MintOfferFfi sse_decode_mint_offer_ffi(SseDeserializer deserializer);

  @protected
  MintRequestFfi sse_decode_mint_request_ffi(SseDeserializer deserializer);

  @protected
  MintRequestStateFfi sse_decode_mint_request_state_ffi(
    SseDeserializer deserializer,
  );

  @protected
  MintRequestStateResponse sse_decode_mint_request_state_response(
    SseDeserializer deserializer,
  );

  @protected
  MintRequestStatusFfi sse_decode_mint_request_status_ffi(
    SseDeserializer deserializer,
  );

  @protected
  NewContactPayload sse_decode_new_contact_payload(
    SseDeserializer deserializer,
  );

  @protected
  NewIdentityPayload sse_decode_new_identity_payload(
    SseDeserializer deserializer,
  );

  @protected
  NotificationFfi sse_decode_notification_ffi(SseDeserializer deserializer);

  @protected
  NotificationFiltersFfi sse_decode_notification_filters_ffi(
    SseDeserializer deserializer,
  );

  @protected
  NotificationLevelFfi sse_decode_notification_level_ffi(
    SseDeserializer deserializer,
  );

  @protected
  NotificationStatusFfi sse_decode_notification_status_ffi(
    SseDeserializer deserializer,
  );

  @protected
  NotificationSubscriptionResponse
  sse_decode_notification_subscription_response(SseDeserializer deserializer);

  @protected
  NotificationTypeFfi sse_decode_notification_type_ffi(
    SseDeserializer deserializer,
  );

  @protected
  OfferToSellBitcreditBillPayload
  sse_decode_offer_to_sell_bitcredit_bill_payload(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BillCurrentWaitingStateFfi?
  sse_decode_opt_box_autoadd_bill_current_waiting_state_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillHistoryBlockPaymentDataFfi?
  sse_decode_opt_box_autoadd_bill_history_block_payment_data_ffi(
    SseDeserializer deserializer,
  );

  @protected
  BillParticipantFfi? sse_decode_opt_box_autoadd_bill_participant_ffi(
    SseDeserializer deserializer,
  );

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  CreatePostalAddressFfi? sse_decode_opt_box_autoadd_create_postal_address_ffi(
    SseDeserializer deserializer,
  );

  @protected
  DateRange? sse_decode_opt_box_autoadd_date_range(
    SseDeserializer deserializer,
  );

  @protected
  FileFfi? sse_decode_opt_box_autoadd_file_ffi(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LightBillParticipantFfi?
  sse_decode_opt_box_autoadd_light_bill_participant_ffi(
    SseDeserializer deserializer,
  );

  @protected
  LightBillSignatoryFfi? sse_decode_opt_box_autoadd_light_bill_signatory_ffi(
    SseDeserializer deserializer,
  );

  @protected
  MintOfferFfi? sse_decode_opt_box_autoadd_mint_offer_ffi(
    SseDeserializer deserializer,
  );

  @protected
  NotificationFfi? sse_decode_opt_box_autoadd_notification_ffi(
    SseDeserializer deserializer,
  );

  @protected
  PendingContactShareFfi? sse_decode_opt_box_autoadd_pending_contact_share_ffi(
    SseDeserializer deserializer,
  );

  @protected
  PostalAddressFfi? sse_decode_opt_box_autoadd_postal_address_ffi(
    SseDeserializer deserializer,
  );

  @protected
  SwitchIdentityTypeFfi? sse_decode_opt_box_autoadd_switch_identity_type_ffi(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  OptionalPostalAddressFfi sse_decode_optional_postal_address_ffi(
    SseDeserializer deserializer,
  );

  @protected
  OverviewBalanceResponse sse_decode_overview_balance_response(
    SseDeserializer deserializer,
  );

  @protected
  OverviewResponse sse_decode_overview_response(SseDeserializer deserializer);

  @protected
  PastEndorseeFfi sse_decode_past_endorsee_ffi(SseDeserializer deserializer);

  @protected
  PastEndorseesResponse sse_decode_past_endorsees_response(
    SseDeserializer deserializer,
  );

  @protected
  PastPaymentDataPaymentFfi sse_decode_past_payment_data_payment_ffi(
    SseDeserializer deserializer,
  );

  @protected
  PastPaymentDataRecourseFfi sse_decode_past_payment_data_recourse_ffi(
    SseDeserializer deserializer,
  );

  @protected
  PastPaymentDataSellFfi sse_decode_past_payment_data_sell_ffi(
    SseDeserializer deserializer,
  );

  @protected
  PastPaymentResultFfi sse_decode_past_payment_result_ffi(
    SseDeserializer deserializer,
  );

  @protected
  PastPaymentsResponse sse_decode_past_payments_response(
    SseDeserializer deserializer,
  );

  @protected
  PaymentStatusFfi sse_decode_payment_status_ffi(SseDeserializer deserializer);

  @protected
  PendingContactShareFfi sse_decode_pending_contact_share_ffi(
    SseDeserializer deserializer,
  );

  @protected
  PendingContactSharesResponse sse_decode_pending_contact_shares_response(
    SseDeserializer deserializer,
  );

  @protected
  PostalAddressFfi sse_decode_postal_address_ffi(SseDeserializer deserializer);

  @protected
  RejectActionBillPayload sse_decode_reject_action_bill_payload(
    SseDeserializer deserializer,
  );

  @protected
  RemoveSignatoryPayload sse_decode_remove_signatory_payload(
    SseDeserializer deserializer,
  );

  @protected
  RequestRecourseForAcceptancePayload
  sse_decode_request_recourse_for_acceptance_payload(
    SseDeserializer deserializer,
  );

  @protected
  RequestRecourseForPaymentPayload
  sse_decode_request_recourse_for_payment_payload(SseDeserializer deserializer);

  @protected
  RequestToAcceptBitcreditBillPayload
  sse_decode_request_to_accept_bitcredit_bill_payload(
    SseDeserializer deserializer,
  );

  @protected
  RequestToMintBitcreditBillPayload
  sse_decode_request_to_mint_bitcredit_bill_payload(
    SseDeserializer deserializer,
  );

  @protected
  RequestToPayAsMintBitcreditBillPayload
  sse_decode_request_to_pay_as_mint_bitcredit_bill_payload(
    SseDeserializer deserializer,
  );

  @protected
  RequestToPayBitcreditBillPayload
  sse_decode_request_to_pay_bitcredit_bill_payload(
    SseDeserializer deserializer,
  );

  @protected
  ResyncBillPayload sse_decode_resync_bill_payload(
    SseDeserializer deserializer,
  );

  @protected
  ResyncCompanyPayload sse_decode_resync_company_payload(
    SseDeserializer deserializer,
  );

  @protected
  SearchContactsPayload sse_decode_search_contacts_payload(
    SseDeserializer deserializer,
  );

  @protected
  SeedPhrase sse_decode_seed_phrase(SseDeserializer deserializer);

  @protected
  ShareBillWithCourtPayload sse_decode_share_bill_with_court_payload(
    SseDeserializer deserializer,
  );

  @protected
  ShareCompanyContactTo sse_decode_share_company_contact_to(
    SseDeserializer deserializer,
  );

  @protected
  ShareContactTo sse_decode_share_contact_to(SseDeserializer deserializer);

  @protected
  SignatoryResponse sse_decode_signatory_response(SseDeserializer deserializer);

  @protected
  StatusResponse sse_decode_status_response(SseDeserializer deserializer);

  @protected
  SwitchIdentity sse_decode_switch_identity(SseDeserializer deserializer);

  @protected
  SwitchIdentityTypeFfi sse_decode_switch_identity_type_ffi(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UploadFile sse_decode_upload_file(SseDeserializer deserializer);

  @protected
  UploadFileResponse sse_decode_upload_file_response(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VerifyEmailPayload sse_decode_verify_email_payload(
    SseDeserializer deserializer,
  );

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_DartFn_Inputs_notification_subscription_response_Output_unit_AnyhowException(
    FutureOr<void> Function(NotificationSubscriptionResponse) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_accept_bitcredit_bill_payload(
    AcceptBitcreditBillPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_accept_company_invite_payload(
    AcceptCompanyInvitePayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_approve_contact_share_payload(
    ApproveContactSharePayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_balance_response(
    BalanceResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_base_64_file_response(
    Base64FileResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_accept_state_ffi(
    BillAcceptStateFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_acceptance_status_ffi(
    BillAcceptanceStatusFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_anon_participant_ffi(
    BillAnonParticipantFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_caller_actions_ffi(
    BillCallerActionsFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_caller_bill_action_ffi(
    BillCallerBillActionFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_caller_payment_action_ffi(
    BillCallerPaymentActionFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_caller_payment_ffi(
    BillCallerPaymentFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_caller_payment_state_ffi(
    BillCallerPaymentStateFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_check_sweep_btc_funds_payload(
    BillCheckSweepBTCFundsPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_combined_bitcoin_key_ffi(
    BillCombinedBitcoinKeyFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_current_waiting_state_ffi(
    BillCurrentWaitingStateFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_data_ffi(BillDataFfi self, SseSerializer serializer);

  @protected
  void sse_encode_bill_history_block_ffi(
    BillHistoryBlockFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_history_block_payment_data_ffi(
    BillHistoryBlockPaymentDataFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_history_response(
    BillHistoryResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_id_response(
    BillIdResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_ident_participant_ffi(
    BillIdentParticipantFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_mint_state_ffi(
    BillMintStateFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_mint_status_ffi(
    BillMintStatusFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_op_code_ffi(
    BillOpCodeFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_participant_ffi(
    BillParticipantFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_participants_ffi(
    BillParticipantsFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_payment_state_ffi(
    BillPaymentStateFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_payment_status_ffi(
    BillPaymentStatusFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_recourse_status_ffi(
    BillRecourseStatusFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_sell_status_ffi(
    BillSellStatusFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_state_ffi(BillStateFfi self, SseSerializer serializer);

  @protected
  void sse_encode_bill_status_ffi(BillStatusFfi self, SseSerializer serializer);

  @protected
  void sse_encode_bill_sweep_btc_estimate_ffi(
    BillSweepBTCEstimateFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_sweep_btc_funds_payload(
    BillSweepBTCFundsPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_sweep_btc_funds_result_ffi(
    BillSweepBTCFundsResultFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_sweep_btc_option_ffi(
    BillSweepBTCOptionFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_waiting_for_payment_state_ffi(
    BillWaitingForPaymentStateFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_waiting_for_recourse_state_ffi(
    BillWaitingForRecourseStateFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_waiting_for_sell_state_ffi(
    BillWaitingForSellStateFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bill_waiting_state_payment_data_ffi(
    BillWaitingStatePaymentDataFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bills_filter_role_ffi(
    BillsFilterRoleFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bills_response(BillsResponse self, SseSerializer serializer);

  @protected
  void sse_encode_bills_search_filter(
    BillsSearchFilter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bills_search_filter_payload(
    BillsSearchFilterPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_binary_file_response(
    BinaryFileResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bitcredit_bill_ffi(
    BitcreditBillFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bitcredit_bill_payload(
    BitcreditBillPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_accept_bitcredit_bill_payload(
    AcceptBitcreditBillPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_accept_company_invite_payload(
    AcceptCompanyInvitePayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_approve_contact_share_payload(
    ApproveContactSharePayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bill_anon_participant_ffi(
    BillAnonParticipantFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bill_caller_payment_ffi(
    BillCallerPaymentFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bill_caller_payment_state_ffi(
    BillCallerPaymentStateFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bill_check_sweep_btc_funds_payload(
    BillCheckSweepBTCFundsPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bill_current_waiting_state_ffi(
    BillCurrentWaitingStateFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bill_history_block_payment_data_ffi(
    BillHistoryBlockPaymentDataFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bill_ident_participant_ffi(
    BillIdentParticipantFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bill_participant_ffi(
    BillParticipantFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bill_sweep_btc_funds_payload(
    BillSweepBTCFundsPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bill_waiting_for_payment_state_ffi(
    BillWaitingForPaymentStateFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bill_waiting_for_recourse_state_ffi(
    BillWaitingForRecourseStateFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bill_waiting_for_sell_state_ffi(
    BillWaitingForSellStateFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bills_search_filter_payload(
    BillsSearchFilterPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bitcredit_bill_payload(
    BitcreditBillPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_btc_address_and_sum_payload(
    BtcAddressAndSumPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_btc_address_payload(
    BtcAddressPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_change_identity_email_payload(
    ChangeIdentityEmailPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_change_identity_payload(
    ChangeIdentityPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_change_signatory_email_payload(
    ChangeSignatoryEmailPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_company_confirm_email_payload(
    CompanyConfirmEmailPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_company_verify_email_payload(
    CompanyVerifyEmailPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_confirm_email_payload(
    ConfirmEmailPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_create_company_payload(
    CreateCompanyPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_create_optional_postal_address_ffi(
    CreateOptionalPostalAddressFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_create_postal_address_ffi(
    CreatePostalAddressFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_date_range(
    DateRange self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ebill_config(
    EbillConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_edit_company_payload(
    EditCompanyPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_edit_contact_payload(
    EditContactPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_endorse_bitcredit_bill_payload(
    EndorseBitcreditBillPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_file_ffi(FileFfi self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_general_search_filter_payload(
    GeneralSearchFilterPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_identity_email_confirmation_ffi(
    IdentityEmailConfirmationFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_invite_signatory_payload(
    InviteSignatoryPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_light_bill_anon_participant_ffi(
    LightBillAnonParticipantFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_light_bill_ident_participant_with_address_ffi(
    LightBillIdentParticipantWithAddressFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_light_bill_participant_ffi(
    LightBillParticipantFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_light_bill_signatory_ffi(
    LightBillSignatoryFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_locally_hide_signatory_payload(
    LocallyHideSignatoryPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_mint_offer_ffi(
    MintOfferFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_new_contact_payload(
    NewContactPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_new_identity_payload(
    NewIdentityPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_notification_ffi(
    NotificationFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_notification_filters_ffi(
    NotificationFiltersFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_offer_to_sell_bitcredit_bill_payload(
    OfferToSellBitcreditBillPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_optional_postal_address_ffi(
    OptionalPostalAddressFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_past_payment_data_payment_ffi(
    PastPaymentDataPaymentFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_past_payment_data_recourse_ffi(
    PastPaymentDataRecourseFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_past_payment_data_sell_ffi(
    PastPaymentDataSellFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pending_contact_share_ffi(
    PendingContactShareFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_postal_address_ffi(
    PostalAddressFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_reject_action_bill_payload(
    RejectActionBillPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_remove_signatory_payload(
    RemoveSignatoryPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_request_recourse_for_acceptance_payload(
    RequestRecourseForAcceptancePayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_request_recourse_for_payment_payload(
    RequestRecourseForPaymentPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_request_to_accept_bitcredit_bill_payload(
    RequestToAcceptBitcreditBillPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_request_to_mint_bitcredit_bill_payload(
    RequestToMintBitcreditBillPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_request_to_pay_as_mint_bitcredit_bill_payload(
    RequestToPayAsMintBitcreditBillPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_request_to_pay_bitcredit_bill_payload(
    RequestToPayBitcreditBillPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_resync_bill_payload(
    ResyncBillPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_resync_company_payload(
    ResyncCompanyPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_search_contacts_payload(
    SearchContactsPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_seed_phrase(
    SeedPhrase self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_share_bill_with_court_payload(
    ShareBillWithCourtPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_share_company_contact_to(
    ShareCompanyContactTo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_share_contact_to(
    ShareContactTo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_switch_identity(
    SwitchIdentity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_switch_identity_type_ffi(
    SwitchIdentityTypeFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_upload_file(
    UploadFile self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_verify_email_payload(
    VerifyEmailPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_btc_address_and_sum_payload(
    BtcAddressAndSumPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_btc_address_payload(
    BtcAddressPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_change_identity_email_payload(
    ChangeIdentityEmailPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_change_identity_payload(
    ChangeIdentityPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_change_signatory_email_payload(
    ChangeSignatoryEmailPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_companies_response(
    CompaniesResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_company_confirm_email_payload(
    CompanyConfirmEmailPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_company_ffi(CompanyFfi self, SseSerializer serializer);

  @protected
  void sse_encode_company_keys_ffi(
    CompanyKeysFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_company_signatory_ffi(
    CompanySignatoryFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_company_signatory_status_ffi(
    CompanySignatoryStatusFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_company_status_ffi(
    CompanyStatusFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_company_verify_email_payload(
    CompanyVerifyEmailPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_confirm_email_payload(
    ConfirmEmailPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_contact_ffi(ContactFfi self, SseSerializer serializer);

  @protected
  void sse_encode_contact_type_ffi(
    ContactTypeFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_contacts_response(
    ContactsResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_create_company_payload(
    CreateCompanyPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_create_optional_postal_address_ffi(
    CreateOptionalPostalAddressFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_create_postal_address_ffi(
    CreatePostalAddressFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_currencies_response(
    CurrenciesResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_currency_response(
    CurrencyResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_date_range(DateRange self, SseSerializer serializer);

  @protected
  void sse_encode_ebill_config(EbillConfig self, SseSerializer serializer);

  @protected
  void sse_encode_ebill_ffi_error(EbillFfiError self, SseSerializer serializer);

  @protected
  void sse_encode_ebill_ffi_error_code(
    EbillFfiErrorCode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ebill_ffi_error_kind(
    EbillFfiErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_edit_company_payload(
    EditCompanyPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_edit_contact_payload(
    EditContactPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_edit_optional_field_mode_ffi(
    EditOptionalFieldModeFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_endorse_bitcredit_bill_payload(
    EndorseBitcreditBillPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_endorsement_ffi(
    EndorsementFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_endorsements_response(
    EndorsementsResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_file_ffi(FileFfi self, SseSerializer serializer);

  @protected
  void sse_encode_general_search_filter(
    GeneralSearchFilter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_general_search_filter_item_type_ffi(
    GeneralSearchFilterItemTypeFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_general_search_filter_payload(
    GeneralSearchFilterPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_general_search_response(
    GeneralSearchResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_identity_email_confirmation_ffi(
    IdentityEmailConfirmationFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_identity_ffi(IdentityFfi self, SseSerializer serializer);

  @protected
  void sse_encode_identity_type_ffi(
    IdentityTypeFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_invite_signatory_payload(
    InviteSignatoryPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_light_bill_anon_participant_ffi(
    LightBillAnonParticipantFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_light_bill_ident_participant_ffi(
    LightBillIdentParticipantFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_light_bill_ident_participant_with_address_ffi(
    LightBillIdentParticipantWithAddressFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_light_bill_participant_ffi(
    LightBillParticipantFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_light_bill_signatory_ffi(
    LightBillSignatoryFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_light_bills_response(
    LightBillsResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_light_bitcredit_bill_ffi(
    LightBitcreditBillFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_light_signed_by_ffi(
    LightSignedByFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_link_to_pay_response(
    LinkToPayResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bill_caller_bill_action_ffi(
    List<BillCallerBillActionFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bill_caller_payment_action_ffi(
    List<BillCallerPaymentActionFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bill_combined_bitcoin_key_ffi(
    List<BillCombinedBitcoinKeyFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bill_history_block_ffi(
    List<BillHistoryBlockFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bitcredit_bill_ffi(
    List<BitcreditBillFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_company_ffi(
    List<CompanyFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_company_signatory_ffi(
    List<CompanySignatoryFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_contact_ffi(
    List<ContactFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_currency_response(
    List<CurrencyResponse> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_endorsement_ffi(
    List<EndorsementFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_file_ffi(List<FileFfi> self, SseSerializer serializer);

  @protected
  void sse_encode_list_general_search_filter_item_type_ffi(
    List<GeneralSearchFilterItemTypeFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_identity_email_confirmation_ffi(
    List<IdentityEmailConfirmationFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_light_bitcredit_bill_ffi(
    List<LightBitcreditBillFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mint_request_state_ffi(
    List<MintRequestStateFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_notification_ffi(
    List<NotificationFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_notification_status_ffi(
    List<NotificationStatusFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_past_endorsee_ffi(
    List<PastEndorseeFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_past_payment_result_ffi(
    List<PastPaymentResultFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_pending_contact_share_ffi(
    List<PendingContactShareFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_signatories_response(
    ListSignatoriesResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_signatory_response(
    List<SignatoryResponse> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_locally_hide_signatory_payload(
    LocallyHideSignatoryPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mempool_link_response(
    MempoolLinkResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mint_offer_ffi(MintOfferFfi self, SseSerializer serializer);

  @protected
  void sse_encode_mint_request_ffi(
    MintRequestFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mint_request_state_ffi(
    MintRequestStateFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mint_request_state_response(
    MintRequestStateResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mint_request_status_ffi(
    MintRequestStatusFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_new_contact_payload(
    NewContactPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_new_identity_payload(
    NewIdentityPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_notification_ffi(
    NotificationFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_notification_filters_ffi(
    NotificationFiltersFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_notification_level_ffi(
    NotificationLevelFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_notification_status_ffi(
    NotificationStatusFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_notification_subscription_response(
    NotificationSubscriptionResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_notification_type_ffi(
    NotificationTypeFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_offer_to_sell_bitcredit_bill_payload(
    OfferToSellBitcreditBillPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bill_current_waiting_state_ffi(
    BillCurrentWaitingStateFfi? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bill_history_block_payment_data_ffi(
    BillHistoryBlockPaymentDataFfi? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bill_participant_ffi(
    BillParticipantFfi? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_create_postal_address_ffi(
    CreatePostalAddressFfi? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_date_range(
    DateRange? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_file_ffi(
    FileFfi? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_light_bill_participant_ffi(
    LightBillParticipantFfi? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_light_bill_signatory_ffi(
    LightBillSignatoryFfi? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_mint_offer_ffi(
    MintOfferFfi? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_notification_ffi(
    NotificationFfi? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_pending_contact_share_ffi(
    PendingContactShareFfi? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_postal_address_ffi(
    PostalAddressFfi? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_switch_identity_type_ffi(
    SwitchIdentityTypeFfi? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_usize(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_optional_postal_address_ffi(
    OptionalPostalAddressFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_overview_balance_response(
    OverviewBalanceResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_overview_response(
    OverviewResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_past_endorsee_ffi(
    PastEndorseeFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_past_endorsees_response(
    PastEndorseesResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_past_payment_data_payment_ffi(
    PastPaymentDataPaymentFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_past_payment_data_recourse_ffi(
    PastPaymentDataRecourseFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_past_payment_data_sell_ffi(
    PastPaymentDataSellFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_past_payment_result_ffi(
    PastPaymentResultFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_past_payments_response(
    PastPaymentsResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_payment_status_ffi(
    PaymentStatusFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pending_contact_share_ffi(
    PendingContactShareFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pending_contact_shares_response(
    PendingContactSharesResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_postal_address_ffi(
    PostalAddressFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reject_action_bill_payload(
    RejectActionBillPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_remove_signatory_payload(
    RemoveSignatoryPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_request_recourse_for_acceptance_payload(
    RequestRecourseForAcceptancePayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_request_recourse_for_payment_payload(
    RequestRecourseForPaymentPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_request_to_accept_bitcredit_bill_payload(
    RequestToAcceptBitcreditBillPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_request_to_mint_bitcredit_bill_payload(
    RequestToMintBitcreditBillPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_request_to_pay_as_mint_bitcredit_bill_payload(
    RequestToPayAsMintBitcreditBillPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_request_to_pay_bitcredit_bill_payload(
    RequestToPayBitcreditBillPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_resync_bill_payload(
    ResyncBillPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_resync_company_payload(
    ResyncCompanyPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_contacts_payload(
    SearchContactsPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_seed_phrase(SeedPhrase self, SseSerializer serializer);

  @protected
  void sse_encode_share_bill_with_court_payload(
    ShareBillWithCourtPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_share_company_contact_to(
    ShareCompanyContactTo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_share_contact_to(
    ShareContactTo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_signatory_response(
    SignatoryResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_status_response(
    StatusResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_switch_identity(
    SwitchIdentity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_switch_identity_type_ffi(
    SwitchIdentityTypeFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_upload_file(UploadFile self, SseSerializer serializer);

  @protected
  void sse_encode_upload_file_response(
    UploadFileResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_verify_email_payload(
    VerifyEmailPayload self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
