// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../data.dart';
import '../data/bill.dart';
import '../data/contact.dart';
import '../data/mint.dart';
import '../data/notification.dart';
import '../error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `endorse`, `get_attachment`, `get_signer_public_data_and_keys`, `issue_bill`, `offer_to_sell_bill`, `request_recourse`

Future<EndorsementsResponse> endorsements({required String id}) =>
    RustLib.instance.api.crateFfiApiBillEndorsements(id: id);

Future<PastPaymentsResponse> pastPayments({required String id}) =>
    RustLib.instance.api.crateFfiApiBillPastPayments(id: id);

Future<PastEndorseesResponse> pastEndorsees({required String id}) =>
    RustLib.instance.api.crateFfiApiBillPastEndorsees(id: id);

Future<List<BillCombinedBitcoinKeyFfi>> bitcoinKeys({required String id}) =>
    RustLib.instance.api.crateFfiApiBillBitcoinKeys(id: id);

Future<BinaryFileResponse> attachment({
  required String billId,
  required String fileName,
}) => RustLib.instance.api.crateFfiApiBillAttachment(
  billId: billId,
  fileName: fileName,
);

Future<Base64FileResponse> attachmentBase64({
  required String billId,
  required String fileName,
}) => RustLib.instance.api.crateFfiApiBillAttachmentBase64(
  billId: billId,
  fileName: fileName,
);

Future<UploadFileResponse> upload({required UploadFile uploadFile}) =>
    RustLib.instance.api.crateFfiApiBillUpload(uploadFile: uploadFile);

Future<LightBillsResponse> search({
  required BillsSearchFilterPayload filterPayload,
}) => RustLib.instance.api.crateFfiApiBillSearch(filterPayload: filterPayload);

Future<LightBillsResponse> listLight() =>
    RustLib.instance.api.crateFfiApiBillListLight();

Future<BillsResponse> list() => RustLib.instance.api.crateFfiApiBillList();

Future<BitcreditBillFfi> detail({required String id}) =>
    RustLib.instance.api.crateFfiApiBillDetail(id: id);

Future<void> checkPaymentForBill({required String id}) =>
    RustLib.instance.api.crateFfiApiBillCheckPaymentForBill(id: id);

Future<void> checkPayment() =>
    RustLib.instance.api.crateFfiApiBillCheckPayment();

Future<BillIdResponse> issue({required BitcreditBillPayload billPayload}) =>
    RustLib.instance.api.crateFfiApiBillIssue(billPayload: billPayload);

Future<BillIdResponse> issueBlank({
  required BitcreditBillPayload billPayload,
}) => RustLib.instance.api.crateFfiApiBillIssueBlank(billPayload: billPayload);

Future<void> offerToSell({
  required OfferToSellBitcreditBillPayload offerToSellPayload,
}) => RustLib.instance.api.crateFfiApiBillOfferToSell(
  offerToSellPayload: offerToSellPayload,
);

Future<void> offerToSellBlank({
  required OfferToSellBitcreditBillPayload offerToSellPayload,
}) => RustLib.instance.api.crateFfiApiBillOfferToSellBlank(
  offerToSellPayload: offerToSellPayload,
);

Future<void> endorseBill({
  required EndorseBitcreditBillPayload endorseBillPayload,
}) => RustLib.instance.api.crateFfiApiBillEndorseBill(
  endorseBillPayload: endorseBillPayload,
);

Future<void> endorseBillBlank({
  required EndorseBitcreditBillPayload endorseBillPayload,
}) => RustLib.instance.api.crateFfiApiBillEndorseBillBlank(
  endorseBillPayload: endorseBillPayload,
);

Future<void> requestToPay({
  required RequestToPayBitcreditBillPayload requestToPayBillPayload,
}) => RustLib.instance.api.crateFfiApiBillRequestToPay(
  requestToPayBillPayload: requestToPayBillPayload,
);

Future<void> requestToPayAsMint({
  required RequestToPayAsMintBitcreditBillPayload requestToPayBillPayload,
}) => RustLib.instance.api.crateFfiApiBillRequestToPayAsMint(
  requestToPayBillPayload: requestToPayBillPayload,
);

Future<void> requestToAccept({
  required RequestToAcceptBitcreditBillPayload requestToAcceptBillPayload,
}) => RustLib.instance.api.crateFfiApiBillRequestToAccept(
  requestToAcceptBillPayload: requestToAcceptBillPayload,
);

Future<void> accept({required AcceptBitcreditBillPayload acceptBillPayload}) =>
    RustLib.instance.api.crateFfiApiBillAccept(
      acceptBillPayload: acceptBillPayload,
    );

Future<void> requestToMint({
  required RequestToMintBitcreditBillPayload requestToMintBillPayload,
}) => RustLib.instance.api.crateFfiApiBillRequestToMint(
  requestToMintBillPayload: requestToMintBillPayload,
);

Future<MintRequestStateResponse> mintState({required String id}) =>
    RustLib.instance.api.crateFfiApiBillMintState(id: id);

Future<void> checkMintState({required String id}) =>
    RustLib.instance.api.crateFfiApiBillCheckMintState(id: id);

Future<void> cancelRequestToMint({required String mintRequestId}) => RustLib
    .instance
    .api
    .crateFfiApiBillCancelRequestToMint(mintRequestId: mintRequestId);

Future<void> acceptMintOffer({required String mintRequestId}) => RustLib
    .instance
    .api
    .crateFfiApiBillAcceptMintOffer(mintRequestId: mintRequestId);

Future<void> rejectMintOffer({required String mintRequestId}) => RustLib
    .instance
    .api
    .crateFfiApiBillRejectMintOffer(mintRequestId: mintRequestId);

Future<void> rejectToAccept({required RejectActionBillPayload rejectPayload}) =>
    RustLib.instance.api.crateFfiApiBillRejectToAccept(
      rejectPayload: rejectPayload,
    );

Future<void> rejectToPay({required RejectActionBillPayload rejectPayload}) =>
    RustLib.instance.api.crateFfiApiBillRejectToPay(
      rejectPayload: rejectPayload,
    );

Future<void> rejectToBuy({required RejectActionBillPayload rejectPayload}) =>
    RustLib.instance.api.crateFfiApiBillRejectToBuy(
      rejectPayload: rejectPayload,
    );

Future<void> rejectToPayRecourse({
  required RejectActionBillPayload rejectPayload,
}) => RustLib.instance.api.crateFfiApiBillRejectToPayRecourse(
  rejectPayload: rejectPayload,
);

Future<void> requestToRecourseBillPayment({
  required RequestRecourseForPaymentPayload requestRecoursePayload,
}) => RustLib.instance.api.crateFfiApiBillRequestToRecourseBillPayment(
  requestRecoursePayload: requestRecoursePayload,
);

Future<void> requestToRecourseBillAcceptance({
  required RequestRecourseForAcceptancePayload requestRecoursePayload,
}) => RustLib.instance.api.crateFfiApiBillRequestToRecourseBillAcceptance(
  requestRecoursePayload: requestRecoursePayload,
);

Future<void> clearBillCache() =>
    RustLib.instance.api.crateFfiApiBillClearBillCache();

Future<void> syncBillChain({required ResyncBillPayload payload}) =>
    RustLib.instance.api.crateFfiApiBillSyncBillChain(payload: payload);

Future<List<String>> devModeGetFullBillChain({required String billId}) =>
    RustLib.instance.api.crateFfiApiBillDevModeGetFullBillChain(billId: billId);

Future<void> shareBillWithCourt({required ShareBillWithCourtPayload payload}) =>
    RustLib.instance.api.crateFfiApiBillShareBillWithCourt(payload: payload);

Future<BillHistoryResponse> billHistory({required String billId}) =>
    RustLib.instance.api.crateFfiApiBillBillHistory(billId: billId);

Future<BillSweepBTCEstimateFfi> checkAndEstimateBtcSweep({
  required BillCheckSweepBTCFundsPayload payload,
}) => RustLib.instance.api.crateFfiApiBillCheckAndEstimateBtcSweep(
  payload: payload,
);

Future<BillSweepBTCFundsResultFfi> sweepBtcFunds({
  required BillSweepBTCFundsPayload payload,
}) => RustLib.instance.api.crateFfiApiBillSweepBtcFunds(payload: payload);
