// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../data.dart';
import '../data/company.dart';
import '../data/contact.dart';
import '../data/identity.dart';
import '../error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `filter_hidden_signatories_for_companies`, `get_file`

Future<BinaryFileResponse> file({
  required String id,
  required String fileName,
}) => RustLib.instance.api.crateFfiApiCompanyFile(id: id, fileName: fileName);

Future<Base64FileResponse> fileBase64({
  required String id,
  required String fileName,
}) => RustLib.instance.api.crateFfiApiCompanyFileBase64(
  id: id,
  fileName: fileName,
);

Future<UploadFileResponse> upload({required UploadFile uploadFile}) =>
    RustLib.instance.api.crateFfiApiCompanyUpload(uploadFile: uploadFile);

Future<CompaniesResponse> list() =>
    RustLib.instance.api.crateFfiApiCompanyList();

Future<CompaniesResponse> listInvites() =>
    RustLib.instance.api.crateFfiApiCompanyListInvites();

Future<ListSignatoriesResponse> listSignatories({required String id}) =>
    RustLib.instance.api.crateFfiApiCompanyListSignatories(id: id);

Future<CompanyFfi> detail({required String id}) =>
    RustLib.instance.api.crateFfiApiCompanyDetail(id: id);

Future<CompanyKeysFfi> createKeys() =>
    RustLib.instance.api.crateFfiApiCompanyCreateKeys();

Future<CompanyFfi> create({required CreateCompanyPayload companyPayload}) =>
    RustLib.instance.api.crateFfiApiCompanyCreate(
      companyPayload: companyPayload,
    );

Future<void> edit({required EditCompanyPayload companyPayload}) =>
    RustLib.instance.api.crateFfiApiCompanyEdit(companyPayload: companyPayload);

Future<void> inviteSignatory({
  required InviteSignatoryPayload companyPayload,
}) => RustLib.instance.api.crateFfiApiCompanyInviteSignatory(
  companyPayload: companyPayload,
);

Future<void> removeSignatory({
  required RemoveSignatoryPayload companyPayload,
}) => RustLib.instance.api.crateFfiApiCompanyRemoveSignatory(
  companyPayload: companyPayload,
);

Future<void> shareContactDetails({required ShareCompanyContactTo shareTo}) =>
    RustLib.instance.api.crateFfiApiCompanyShareContactDetails(
      shareTo: shareTo,
    );

Future<List<String>> devModeGetFullCompanyChain({required String companyId}) =>
    RustLib.instance.api.crateFfiApiCompanyDevModeGetFullCompanyChain(
      companyId: companyId,
    );

Future<void> syncCompanyChain({required ResyncCompanyPayload payload}) =>
    RustLib.instance.api.crateFfiApiCompanySyncCompanyChain(payload: payload);

Future<void> changeSignatoryEmail({
  required ChangeSignatoryEmailPayload payload,
}) => RustLib.instance.api.crateFfiApiCompanyChangeSignatoryEmail(
  payload: payload,
);

Future<void> confirmEmail({required CompanyConfirmEmailPayload payload}) =>
    RustLib.instance.api.crateFfiApiCompanyConfirmEmail(payload: payload);

Future<void> verifyEmail({required CompanyVerifyEmailPayload payload}) =>
    RustLib.instance.api.crateFfiApiCompanyVerifyEmail(payload: payload);

Future<List<IdentityEmailConfirmationFfi>> getEmailConfirmations({
  required String companyId,
}) => RustLib.instance.api.crateFfiApiCompanyGetEmailConfirmations(
  companyId: companyId,
);

Future<void> acceptInvite({required AcceptCompanyInvitePayload payload}) =>
    RustLib.instance.api.crateFfiApiCompanyAcceptInvite(payload: payload);

Future<void> rejectInvite({required String companyId}) =>
    RustLib.instance.api.crateFfiApiCompanyRejectInvite(companyId: companyId);

Future<void> locallyHideSignatory({
  required LocallyHideSignatoryPayload payload,
}) => RustLib.instance.api.crateFfiApiCompanyLocallyHideSignatory(
  payload: payload,
);
