// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../data.dart';
import '../data/contact.dart';
import '../error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_file`

Future<BinaryFileResponse> file({
  required String nodeId,
  required String fileName,
}) => RustLib.instance.api.crateFfiApiContactFile(
  nodeId: nodeId,
  fileName: fileName,
);

Future<Base64FileResponse> fileBase64({
  required String nodeId,
  required String fileName,
}) => RustLib.instance.api.crateFfiApiContactFileBase64(
  nodeId: nodeId,
  fileName: fileName,
);

Future<UploadFileResponse> upload({required UploadFile uploadFile}) =>
    RustLib.instance.api.crateFfiApiContactUpload(uploadFile: uploadFile);

Future<ContactsResponse> list() =>
    RustLib.instance.api.crateFfiApiContactList();

Future<ContactsResponse> search({required SearchContactsPayload query}) =>
    RustLib.instance.api.crateFfiApiContactSearch(query: query);

Future<ContactFfi> detail({required String nodeId}) =>
    RustLib.instance.api.crateFfiApiContactDetail(nodeId: nodeId);

Future<void> remove({required String nodeId}) =>
    RustLib.instance.api.crateFfiApiContactRemove(nodeId: nodeId);

Future<ContactFfi> deanonymize({required NewContactPayload contactPayload}) =>
    RustLib.instance.api.crateFfiApiContactDeanonymize(
      contactPayload: contactPayload,
    );

Future<ContactFfi> create({required NewContactPayload contactPayload}) =>
    RustLib.instance.api.crateFfiApiContactCreate(
      contactPayload: contactPayload,
    );

Future<void> edit({required EditContactPayload contactPayload}) =>
    RustLib.instance.api.crateFfiApiContactEdit(contactPayload: contactPayload);

Future<PendingContactSharesResponse> listPendingContactShares({
  required String receiverNodeId,
}) => RustLib.instance.api.crateFfiApiContactListPendingContactShares(
  receiverNodeId: receiverNodeId,
);

Future<PendingContactShareFfi?> getPendingContactShare({required String id}) =>
    RustLib.instance.api.crateFfiApiContactGetPendingContactShare(id: id);

Future<void> approveContactShare({
  required ApproveContactSharePayload approvePayload,
}) => RustLib.instance.api.crateFfiApiContactApproveContactShare(
  approvePayload: approvePayload,
);

Future<void> rejectContactShare({required String pendingShareId}) => RustLib
    .instance
    .api
    .crateFfiApiContactRejectContactShare(pendingShareId: pendingShareId);
