// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../data.dart';
import '../data/bill.dart';
import '../data/company.dart';
import '../data/contact.dart';
import '../data/identity.dart';
import '../data/notification.dart';
import '../error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<StatusResponse> getStatus() =>
    RustLib.instance.api.crateFfiApiGeneralGetStatus();

Future<CurrenciesResponse> currencies() =>
    RustLib.instance.api.crateFfiApiGeneralCurrencies();

Future<BinaryFileResponse> tempFile({required String fileUploadId}) =>
    RustLib.instance.api.crateFfiApiGeneralTempFile(fileUploadId: fileUploadId);

Future<OverviewResponse> overview({required String currency}) =>
    RustLib.instance.api.crateFfiApiGeneralOverview(currency: currency);

Future<GeneralSearchResponse> search({
  required GeneralSearchFilterPayload searchFilter,
}) => RustLib.instance.api.crateFfiApiGeneralSearch(searchFilter: searchFilter);

Future<LinkToPayResponse> linkToPay({required BtcAddressAndSumPayload pl}) =>
    RustLib.instance.api.crateFfiApiGeneralLinkToPay(pl: pl);

Future<MempoolLinkResponse> mempoolLink({required BtcAddressPayload pl}) =>
    RustLib.instance.api.crateFfiApiGeneralMempoolLink(pl: pl);
