// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../data.dart';
import '../data/identity.dart';
import '../error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_file`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SwitchIdentityState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `get_current_identity_node_id`, `get_current_identity`

Future<BinaryFileResponse> file({required String fileName}) =>
    RustLib.instance.api.crateFfiApiIdentityFile(fileName: fileName);

Future<Base64FileResponse> fileBase64({required String fileName}) =>
    RustLib.instance.api.crateFfiApiIdentityFileBase64(fileName: fileName);

Future<UploadFileResponse> upload({required UploadFile uploadFile}) =>
    RustLib.instance.api.crateFfiApiIdentityUpload(uploadFile: uploadFile);

Future<IdentityFfi> detail() =>
    RustLib.instance.api.crateFfiApiIdentityDetail();

Future<IdentityFfi> deanonymize({required NewIdentityPayload identity}) =>
    RustLib.instance.api.crateFfiApiIdentityDeanonymize(identity: identity);

Future<IdentityFfi> create({required NewIdentityPayload identity}) =>
    RustLib.instance.api.crateFfiApiIdentityCreate(identity: identity);

Future<void> change({required ChangeIdentityPayload identityPayload}) => RustLib
    .instance
    .api
    .crateFfiApiIdentityChange(identityPayload: identityPayload);

Future<void> changeEmail({
  required ChangeIdentityEmailPayload identityEmailPayload,
}) => RustLib.instance.api.crateFfiApiIdentityChangeEmail(
  identityEmailPayload: identityEmailPayload,
);

Future<SwitchIdentity> active() =>
    RustLib.instance.api.crateFfiApiIdentityActive();

Future<void> switch_({required SwitchIdentity payload}) =>
    RustLib.instance.api.crateFfiApiIdentitySwitch(payload: payload);

Future<SeedPhrase> seedBackup() =>
    RustLib.instance.api.crateFfiApiIdentitySeedBackup();

Future<void> seedRecover({required SeedPhrase seedPhrasePayload}) => RustLib
    .instance
    .api
    .crateFfiApiIdentitySeedRecover(seedPhrasePayload: seedPhrasePayload);

Future<void> shareContactDetails({required ShareContactTo shareContactTo}) =>
    RustLib.instance.api.crateFfiApiIdentityShareContactDetails(
      shareContactTo: shareContactTo,
    );

Future<List<String>> devModeGetFullIdentityChain() =>
    RustLib.instance.api.crateFfiApiIdentityDevModeGetFullIdentityChain();

Future<void> syncIdentityChain() =>
    RustLib.instance.api.crateFfiApiIdentitySyncIdentityChain();

Future<void> confirmEmail({required ConfirmEmailPayload payload}) =>
    RustLib.instance.api.crateFfiApiIdentityConfirmEmail(payload: payload);

Future<void> verifyEmail({required VerifyEmailPayload payload}) =>
    RustLib.instance.api.crateFfiApiIdentityVerifyEmail(payload: payload);

Future<List<IdentityEmailConfirmationFfi>> getEmailConfirmations() =>
    RustLib.instance.api.crateFfiApiIdentityGetEmailConfirmations();
