// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../data.dart';
import '../data/notification.dart';
import '../error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<List<NotificationStatusFfi>> activeNotificationsForNodeIds({
  required List<String> nodeIds,
}) => RustLib.instance.api.crateFfiApiNotificationActiveNotificationsForNodeIds(
  nodeIds: nodeIds,
);

Future<void> subscribe({
  required FutureOr<void> Function(NotificationSubscriptionResponse) callback,
}) => RustLib.instance.api.crateFfiApiNotificationSubscribe(callback: callback);

Future<List<NotificationFfi>> list({required NotificationFiltersFfi filters}) =>
    RustLib.instance.api.crateFfiApiNotificationList(filters: filters);

Future<void> markAsDone({required String notificationId}) => RustLib
    .instance
    .api
    .crateFfiApiNotificationMarkAsDone(notificationId: notificationId);

/// Fetch email notifications preferences link for the currently selected identity
Future<String> getEmailNotificationsPreferencesLink() => RustLib.instance.api
    .crateFfiApiNotificationGetEmailNotificationsPreferencesLink();

class NotificationSubscriptionResponse {
  final String value;

  const NotificationSubscriptionResponse({required this.value});

  @override
  int get hashCode => value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotificationSubscriptionResponse &&
          runtimeType == other.runtimeType &&
          value == other.value;
}
