[package]
name = "bcr-ebill-persistence"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
doctest = false

[features]
default = []
sqlite = ["sqlx/sqlite-bundled"]
postgres = ["sqlx/postgres"]
protocol-ws = ["dep:surrealdb", "surrealdb/protocol-ws"]
surrealkv = ["dep:surrealdb", "surrealdb/kv-surrealkv"]

[dependencies]
borsh.workspace = true
async-trait.workspace = true
base64.workspace = true
serde_json.workspace = true
serde.workspace = true
log.workspace = true
thiserror.workspace = true
uuid.workspace = true
futures.workspace = true
nostr.workspace = true
bcr-ebill-core.workspace = true
bcr-common.workspace = true
time.workspace = true
surrealdb = { version = "2.3", optional = true, default-features = false }
tokio.workspace = true
bitcoin.workspace = true
url.workspace = true
arc-swap = "1.7"
sqlx.workspace = true

[dev-dependencies]
surrealdb = { version = "2.3", default-features = false, features = ["kv-mem"] }
tempfile = "3"
