// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../data.dart';
import 'contact.dart';
import 'notification.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'bill.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

class AcceptBitcreditBillPayload {
  final String billId;

  const AcceptBitcreditBillPayload({required this.billId});

  @override
  int get hashCode => billId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AcceptBitcreditBillPayload &&
          runtimeType == other.runtimeType &&
          billId == other.billId;
}

@freezed
sealed class BillAcceptStateFfi with _$BillAcceptStateFfi {
  const BillAcceptStateFfi._();

  const factory BillAcceptStateFfi.none() = BillAcceptStateFfi_None;
  const factory BillAcceptStateFfi.requested(BigInt field0) =
      BillAcceptStateFfi_Requested;
  const factory BillAcceptStateFfi.accepted(BigInt field0) =
      BillAcceptStateFfi_Accepted;
  const factory BillAcceptStateFfi.expired(BigInt field0) =
      BillAcceptStateFfi_Expired;
  const factory BillAcceptStateFfi.rejected(BigInt field0) =
      BillAcceptStateFfi_Rejected;
}

class BillAcceptanceStatusFfi {
  final BigInt? timeOfRequestToAccept;
  final bool requestedToAccept;
  final bool accepted;
  final bool requestToAcceptTimedOut;
  final bool rejectedToAccept;
  final BigInt? acceptanceDeadlineTimestamp;

  const BillAcceptanceStatusFfi({
    this.timeOfRequestToAccept,
    required this.requestedToAccept,
    required this.accepted,
    required this.requestToAcceptTimedOut,
    required this.rejectedToAccept,
    this.acceptanceDeadlineTimestamp,
  });

  @override
  int get hashCode =>
      timeOfRequestToAccept.hashCode ^
      requestedToAccept.hashCode ^
      accepted.hashCode ^
      requestToAcceptTimedOut.hashCode ^
      rejectedToAccept.hashCode ^
      acceptanceDeadlineTimestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillAcceptanceStatusFfi &&
          runtimeType == other.runtimeType &&
          timeOfRequestToAccept == other.timeOfRequestToAccept &&
          requestedToAccept == other.requestedToAccept &&
          accepted == other.accepted &&
          requestToAcceptTimedOut == other.requestToAcceptTimedOut &&
          rejectedToAccept == other.rejectedToAccept &&
          acceptanceDeadlineTimestamp == other.acceptanceDeadlineTimestamp;
}

class BillAnonParticipantFfi {
  final String nodeId;
  final List<String> nostrRelays;

  const BillAnonParticipantFfi({
    required this.nodeId,
    required this.nostrRelays,
  });

  @override
  int get hashCode => nodeId.hashCode ^ nostrRelays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillAnonParticipantFfi &&
          runtimeType == other.runtimeType &&
          nodeId == other.nodeId &&
          nostrRelays == other.nostrRelays;
}

class BillCallerActionsFfi {
  final List<BillCallerBillActionFfi> billActions;
  final List<BillCallerPaymentActionFfi> paymentActions;

  const BillCallerActionsFfi({
    required this.billActions,
    required this.paymentActions,
  });

  @override
  int get hashCode => billActions.hashCode ^ paymentActions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillCallerActionsFfi &&
          runtimeType == other.runtimeType &&
          billActions == other.billActions &&
          paymentActions == other.paymentActions;
}

enum BillCallerBillActionFfi {
  requestAcceptance,
  accept,
  requestToPay,
  offerToSell,
  sell,
  endorse,
  requestRecourseForAcceptance,
  requestRecourseForPayment,
  recourse,
  mint,
  rejectAcceptance,
  rejectPayment,
  rejectBuying,
  rejectPaymentForRecourse,
}

@freezed
sealed class BillCallerPaymentActionFfi with _$BillCallerPaymentActionFfi {
  const BillCallerPaymentActionFfi._();

  const factory BillCallerPaymentActionFfi.pay(BillCallerPaymentFfi field0) =
      BillCallerPaymentActionFfi_Pay;
  const factory BillCallerPaymentActionFfi.checkPayment(
    BillCallerPaymentFfi field0,
  ) = BillCallerPaymentActionFfi_CheckPayment;
}

@freezed
sealed class BillCallerPaymentFfi with _$BillCallerPaymentFfi {
  const BillCallerPaymentFfi._();

  const factory BillCallerPaymentFfi.sell({
    required BillParticipantFfi buyer,
    required BillParticipantFfi seller,
    required BillCallerPaymentStateFfi state,
  }) = BillCallerPaymentFfi_Sell;
  const factory BillCallerPaymentFfi.payment({
    required BillIdentParticipantFfi payer,
    required BillParticipantFfi payee,
    required BillCallerPaymentStateFfi state,
  }) = BillCallerPaymentFfi_Payment;
  const factory BillCallerPaymentFfi.recourse({
    required BillParticipantFfi recourser,
    required BillIdentParticipantFfi recoursee,
    required BillCallerPaymentStateFfi state,
  }) = BillCallerPaymentFfi_Recourse;
}

class BillCallerPaymentStateFfi {
  final BigInt timeOfRequest;
  final String currency;
  final String sum;
  final String addressToPay;
  final PaymentStatusFfi status;
  final BigInt paymentDeadline;
  final String? txId;
  final bool inMempool;
  final BigInt confirmations;
  final String? privateDescriptorToSpend;

  const BillCallerPaymentStateFfi({
    required this.timeOfRequest,
    required this.currency,
    required this.sum,
    required this.addressToPay,
    required this.status,
    required this.paymentDeadline,
    this.txId,
    required this.inMempool,
    required this.confirmations,
    this.privateDescriptorToSpend,
  });

  @override
  int get hashCode =>
      timeOfRequest.hashCode ^
      currency.hashCode ^
      sum.hashCode ^
      addressToPay.hashCode ^
      status.hashCode ^
      paymentDeadline.hashCode ^
      txId.hashCode ^
      inMempool.hashCode ^
      confirmations.hashCode ^
      privateDescriptorToSpend.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillCallerPaymentStateFfi &&
          runtimeType == other.runtimeType &&
          timeOfRequest == other.timeOfRequest &&
          currency == other.currency &&
          sum == other.sum &&
          addressToPay == other.addressToPay &&
          status == other.status &&
          paymentDeadline == other.paymentDeadline &&
          txId == other.txId &&
          inMempool == other.inMempool &&
          confirmations == other.confirmations &&
          privateDescriptorToSpend == other.privateDescriptorToSpend;
}

class BillCheckSweepBTCFundsPayload {
  final String billId;
  final String sourceAddress;
  final String destinationAddress;

  const BillCheckSweepBTCFundsPayload({
    required this.billId,
    required this.sourceAddress,
    required this.destinationAddress,
  });

  @override
  int get hashCode =>
      billId.hashCode ^ sourceAddress.hashCode ^ destinationAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillCheckSweepBTCFundsPayload &&
          runtimeType == other.runtimeType &&
          billId == other.billId &&
          sourceAddress == other.sourceAddress &&
          destinationAddress == other.destinationAddress;
}

class BillCombinedBitcoinKeyFfi {
  final BigInt blockId;
  final BigInt signingTimestamp;
  final BillOpCodeFfi paymentOp;
  final String privateDescriptor;

  const BillCombinedBitcoinKeyFfi({
    required this.blockId,
    required this.signingTimestamp,
    required this.paymentOp,
    required this.privateDescriptor,
  });

  @override
  int get hashCode =>
      blockId.hashCode ^
      signingTimestamp.hashCode ^
      paymentOp.hashCode ^
      privateDescriptor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillCombinedBitcoinKeyFfi &&
          runtimeType == other.runtimeType &&
          blockId == other.blockId &&
          signingTimestamp == other.signingTimestamp &&
          paymentOp == other.paymentOp &&
          privateDescriptor == other.privateDescriptor;
}

@freezed
sealed class BillCurrentWaitingStateFfi with _$BillCurrentWaitingStateFfi {
  const BillCurrentWaitingStateFfi._();

  const factory BillCurrentWaitingStateFfi.sell(
    BillWaitingForSellStateFfi field0,
  ) = BillCurrentWaitingStateFfi_Sell;
  const factory BillCurrentWaitingStateFfi.payment(
    BillWaitingForPaymentStateFfi field0,
  ) = BillCurrentWaitingStateFfi_Payment;
  const factory BillCurrentWaitingStateFfi.recourse(
    BillWaitingForRecourseStateFfi field0,
  ) = BillCurrentWaitingStateFfi_Recourse;
}

class BillDataFfi {
  final BigInt timeOfDrawing;
  final String issueDate;
  final BigInt timeOfMaturity;
  final String maturityDate;
  final String countryOfIssuing;
  final String cityOfIssuing;
  final String countryOfPayment;
  final String cityOfPayment;
  final String currency;
  final String sum;
  final List<FileFfi> files;
  final NotificationFfi? activeNotification;

  const BillDataFfi({
    required this.timeOfDrawing,
    required this.issueDate,
    required this.timeOfMaturity,
    required this.maturityDate,
    required this.countryOfIssuing,
    required this.cityOfIssuing,
    required this.countryOfPayment,
    required this.cityOfPayment,
    required this.currency,
    required this.sum,
    required this.files,
    this.activeNotification,
  });

  @override
  int get hashCode =>
      timeOfDrawing.hashCode ^
      issueDate.hashCode ^
      timeOfMaturity.hashCode ^
      maturityDate.hashCode ^
      countryOfIssuing.hashCode ^
      cityOfIssuing.hashCode ^
      countryOfPayment.hashCode ^
      cityOfPayment.hashCode ^
      currency.hashCode ^
      sum.hashCode ^
      files.hashCode ^
      activeNotification.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillDataFfi &&
          runtimeType == other.runtimeType &&
          timeOfDrawing == other.timeOfDrawing &&
          issueDate == other.issueDate &&
          timeOfMaturity == other.timeOfMaturity &&
          maturityDate == other.maturityDate &&
          countryOfIssuing == other.countryOfIssuing &&
          cityOfIssuing == other.cityOfIssuing &&
          countryOfPayment == other.countryOfPayment &&
          cityOfPayment == other.cityOfPayment &&
          currency == other.currency &&
          sum == other.sum &&
          files == other.files &&
          activeNotification == other.activeNotification;
}

class BillHistoryBlockFfi {
  final BigInt blockId;
  final BillOpCodeFfi blockType;
  final LightBillParticipantFfi? payToTheOrderOf;
  final BillHistoryBlockPaymentDataFfi? paymentData;
  final BigInt? requestDeadline;
  final LightSignedByFfi signed;
  final BigInt signingTimestamp;
  final PostalAddressFfi? signingAddress;

  const BillHistoryBlockFfi({
    required this.blockId,
    required this.blockType,
    this.payToTheOrderOf,
    this.paymentData,
    this.requestDeadline,
    required this.signed,
    required this.signingTimestamp,
    this.signingAddress,
  });

  @override
  int get hashCode =>
      blockId.hashCode ^
      blockType.hashCode ^
      payToTheOrderOf.hashCode ^
      paymentData.hashCode ^
      requestDeadline.hashCode ^
      signed.hashCode ^
      signingTimestamp.hashCode ^
      signingAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillHistoryBlockFfi &&
          runtimeType == other.runtimeType &&
          blockId == other.blockId &&
          blockType == other.blockType &&
          payToTheOrderOf == other.payToTheOrderOf &&
          paymentData == other.paymentData &&
          requestDeadline == other.requestDeadline &&
          signed == other.signed &&
          signingTimestamp == other.signingTimestamp &&
          signingAddress == other.signingAddress;
}

class BillHistoryBlockPaymentDataFfi {
  final String currency;
  final String sum;
  final String paymentAddress;

  const BillHistoryBlockPaymentDataFfi({
    required this.currency,
    required this.sum,
    required this.paymentAddress,
  });

  @override
  int get hashCode =>
      currency.hashCode ^ sum.hashCode ^ paymentAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillHistoryBlockPaymentDataFfi &&
          runtimeType == other.runtimeType &&
          currency == other.currency &&
          sum == other.sum &&
          paymentAddress == other.paymentAddress;
}

class BillHistoryResponse {
  final List<BillHistoryBlockFfi> blocks;

  const BillHistoryResponse({required this.blocks});

  @override
  int get hashCode => blocks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillHistoryResponse &&
          runtimeType == other.runtimeType &&
          blocks == other.blocks;
}

class BillIdResponse {
  final String id;

  const BillIdResponse({required this.id});

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillIdResponse &&
          runtimeType == other.runtimeType &&
          id == other.id;
}

class BillIdentParticipantFfi {
  final ContactTypeFfi t;
  final String nodeId;
  final String name;
  final PostalAddressFfi postalAddress;
  final String? email;
  final List<String> nostrRelays;

  const BillIdentParticipantFfi({
    required this.t,
    required this.nodeId,
    required this.name,
    required this.postalAddress,
    this.email,
    required this.nostrRelays,
  });

  @override
  int get hashCode =>
      t.hashCode ^
      nodeId.hashCode ^
      name.hashCode ^
      postalAddress.hashCode ^
      email.hashCode ^
      nostrRelays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillIdentParticipantFfi &&
          runtimeType == other.runtimeType &&
          t == other.t &&
          nodeId == other.nodeId &&
          name == other.name &&
          postalAddress == other.postalAddress &&
          email == other.email &&
          nostrRelays == other.nostrRelays;
}

enum BillMintStateFfi { none, requested }

class BillMintStatusFfi {
  final bool hasMintRequests;

  const BillMintStatusFfi({required this.hasMintRequests});

  @override
  int get hashCode => hasMintRequests.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillMintStatusFfi &&
          runtimeType == other.runtimeType &&
          hasMintRequests == other.hasMintRequests;
}

enum BillOpCodeFfi {
  issue,
  accept,
  endorse,
  requestToAccept,
  requestToPay,
  offerToSell,
  sell,
  mint,
  rejectToAccept,
  rejectToPay,
  rejectToBuy,
  rejectToPayRecourse,
  requestRecourse,
  recourse,
}

@freezed
sealed class BillParticipantFfi with _$BillParticipantFfi {
  const BillParticipantFfi._();

  const factory BillParticipantFfi.anon(BillAnonParticipantFfi field0) =
      BillParticipantFfi_Anon;
  const factory BillParticipantFfi.ident(BillIdentParticipantFfi field0) =
      BillParticipantFfi_Ident;
}

class BillParticipantsFfi {
  final BillIdentParticipantFfi drawee;
  final BillIdentParticipantFfi drawer;
  final BillParticipantFfi payee;
  final BillParticipantFfi? endorsee;
  final BigInt endorsementsCount;
  final List<String> allParticipantNodeIds;

  const BillParticipantsFfi({
    required this.drawee,
    required this.drawer,
    required this.payee,
    this.endorsee,
    required this.endorsementsCount,
    required this.allParticipantNodeIds,
  });

  @override
  int get hashCode =>
      drawee.hashCode ^
      drawer.hashCode ^
      payee.hashCode ^
      endorsee.hashCode ^
      endorsementsCount.hashCode ^
      allParticipantNodeIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillParticipantsFfi &&
          runtimeType == other.runtimeType &&
          drawee == other.drawee &&
          drawer == other.drawer &&
          payee == other.payee &&
          endorsee == other.endorsee &&
          endorsementsCount == other.endorsementsCount &&
          allParticipantNodeIds == other.allParticipantNodeIds;
}

@freezed
sealed class BillPaymentStateFfi with _$BillPaymentStateFfi {
  const BillPaymentStateFfi._();

  const factory BillPaymentStateFfi.none() = BillPaymentStateFfi_None;
  const factory BillPaymentStateFfi.requested(BigInt field0) =
      BillPaymentStateFfi_Requested;
  const factory BillPaymentStateFfi.paid(BigInt field0) =
      BillPaymentStateFfi_Paid;
  const factory BillPaymentStateFfi.expired(BigInt field0) =
      BillPaymentStateFfi_Expired;
  const factory BillPaymentStateFfi.rejected(BigInt field0) =
      BillPaymentStateFfi_Rejected;
}

class BillPaymentStatusFfi {
  final BigInt? timeOfRequestToPay;
  final bool requestedToPay;
  final bool paid;
  final bool requestToPayTimedOut;
  final bool rejectedToPay;
  final BigInt? paymentDeadlineTimestamp;

  const BillPaymentStatusFfi({
    this.timeOfRequestToPay,
    required this.requestedToPay,
    required this.paid,
    required this.requestToPayTimedOut,
    required this.rejectedToPay,
    this.paymentDeadlineTimestamp,
  });

  @override
  int get hashCode =>
      timeOfRequestToPay.hashCode ^
      requestedToPay.hashCode ^
      paid.hashCode ^
      requestToPayTimedOut.hashCode ^
      rejectedToPay.hashCode ^
      paymentDeadlineTimestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillPaymentStatusFfi &&
          runtimeType == other.runtimeType &&
          timeOfRequestToPay == other.timeOfRequestToPay &&
          requestedToPay == other.requestedToPay &&
          paid == other.paid &&
          requestToPayTimedOut == other.requestToPayTimedOut &&
          rejectedToPay == other.rejectedToPay &&
          paymentDeadlineTimestamp == other.paymentDeadlineTimestamp;
}

class BillRecourseStatusFfi {
  final BigInt? timeOfLastRequestToRecourse;
  final bool recoursed;
  final bool requestedToRecourse;
  final bool requestToRecourseTimedOut;
  final bool rejectedRequestToRecourse;
  final BigInt? recourseDeadlineTimestamp;

  const BillRecourseStatusFfi({
    this.timeOfLastRequestToRecourse,
    required this.recoursed,
    required this.requestedToRecourse,
    required this.requestToRecourseTimedOut,
    required this.rejectedRequestToRecourse,
    this.recourseDeadlineTimestamp,
  });

  @override
  int get hashCode =>
      timeOfLastRequestToRecourse.hashCode ^
      recoursed.hashCode ^
      requestedToRecourse.hashCode ^
      requestToRecourseTimedOut.hashCode ^
      rejectedRequestToRecourse.hashCode ^
      recourseDeadlineTimestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillRecourseStatusFfi &&
          runtimeType == other.runtimeType &&
          timeOfLastRequestToRecourse == other.timeOfLastRequestToRecourse &&
          recoursed == other.recoursed &&
          requestedToRecourse == other.requestedToRecourse &&
          requestToRecourseTimedOut == other.requestToRecourseTimedOut &&
          rejectedRequestToRecourse == other.rejectedRequestToRecourse &&
          recourseDeadlineTimestamp == other.recourseDeadlineTimestamp;
}

class BillSellStatusFfi {
  final BigInt? timeOfLastOfferToSell;
  final bool sold;
  final bool offeredToSell;
  final bool offerToSellTimedOut;
  final bool rejectedOfferToSell;
  final BigInt? buyingDeadlineTimestamp;

  const BillSellStatusFfi({
    this.timeOfLastOfferToSell,
    required this.sold,
    required this.offeredToSell,
    required this.offerToSellTimedOut,
    required this.rejectedOfferToSell,
    this.buyingDeadlineTimestamp,
  });

  @override
  int get hashCode =>
      timeOfLastOfferToSell.hashCode ^
      sold.hashCode ^
      offeredToSell.hashCode ^
      offerToSellTimedOut.hashCode ^
      rejectedOfferToSell.hashCode ^
      buyingDeadlineTimestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillSellStatusFfi &&
          runtimeType == other.runtimeType &&
          timeOfLastOfferToSell == other.timeOfLastOfferToSell &&
          sold == other.sold &&
          offeredToSell == other.offeredToSell &&
          offerToSellTimedOut == other.offerToSellTimedOut &&
          rejectedOfferToSell == other.rejectedOfferToSell &&
          buyingDeadlineTimestamp == other.buyingDeadlineTimestamp;
}

class BillStateFfi {
  final BillMintStateFfi mint;
  final BillAcceptStateFfi accept;
  final BillPaymentStateFfi payment;

  const BillStateFfi({
    required this.mint,
    required this.accept,
    required this.payment,
  });

  @override
  int get hashCode => mint.hashCode ^ accept.hashCode ^ payment.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillStateFfi &&
          runtimeType == other.runtimeType &&
          mint == other.mint &&
          accept == other.accept &&
          payment == other.payment;
}

class BillStatusFfi {
  final BillAcceptanceStatusFfi acceptance;
  final BillPaymentStatusFfi payment;
  final BillSellStatusFfi sell;
  final BillRecourseStatusFfi recourse;
  final BillMintStatusFfi mint;
  final bool redeemedFundsAvailable;
  final bool hasRequestedFunds;
  final BigInt lastBlockTime;

  const BillStatusFfi({
    required this.acceptance,
    required this.payment,
    required this.sell,
    required this.recourse,
    required this.mint,
    required this.redeemedFundsAvailable,
    required this.hasRequestedFunds,
    required this.lastBlockTime,
  });

  @override
  int get hashCode =>
      acceptance.hashCode ^
      payment.hashCode ^
      sell.hashCode ^
      recourse.hashCode ^
      mint.hashCode ^
      redeemedFundsAvailable.hashCode ^
      hasRequestedFunds.hashCode ^
      lastBlockTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillStatusFfi &&
          runtimeType == other.runtimeType &&
          acceptance == other.acceptance &&
          payment == other.payment &&
          sell == other.sell &&
          recourse == other.recourse &&
          mint == other.mint &&
          redeemedFundsAvailable == other.redeemedFundsAvailable &&
          hasRequestedFunds == other.hasRequestedFunds &&
          lastBlockTime == other.lastBlockTime;
}

class BillSweepBTCEstimateFfi {
  final BigInt availableFunds;
  final BillSweepBTCOptionFfi economy;
  final BillSweepBTCOptionFfi fast;

  const BillSweepBTCEstimateFfi({
    required this.availableFunds,
    required this.economy,
    required this.fast,
  });

  @override
  int get hashCode =>
      availableFunds.hashCode ^ economy.hashCode ^ fast.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillSweepBTCEstimateFfi &&
          runtimeType == other.runtimeType &&
          availableFunds == other.availableFunds &&
          economy == other.economy &&
          fast == other.fast;
}

class BillSweepBTCFundsPayload {
  final String billId;
  final String sourceAddress;
  final String destinationAddress;
  final BigInt fee;

  const BillSweepBTCFundsPayload({
    required this.billId,
    required this.sourceAddress,
    required this.destinationAddress,
    required this.fee,
  });

  @override
  int get hashCode =>
      billId.hashCode ^
      sourceAddress.hashCode ^
      destinationAddress.hashCode ^
      fee.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillSweepBTCFundsPayload &&
          runtimeType == other.runtimeType &&
          billId == other.billId &&
          sourceAddress == other.sourceAddress &&
          destinationAddress == other.destinationAddress &&
          fee == other.fee;
}

class BillSweepBTCFundsResultFfi {
  final String txId;
  final String linkToTx;
  final BigInt feeSat;
  final BigInt sweepAmount;

  const BillSweepBTCFundsResultFfi({
    required this.txId,
    required this.linkToTx,
    required this.feeSat,
    required this.sweepAmount,
  });

  @override
  int get hashCode =>
      txId.hashCode ^
      linkToTx.hashCode ^
      feeSat.hashCode ^
      sweepAmount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillSweepBTCFundsResultFfi &&
          runtimeType == other.runtimeType &&
          txId == other.txId &&
          linkToTx == other.linkToTx &&
          feeSat == other.feeSat &&
          sweepAmount == other.sweepAmount;
}

class BillSweepBTCOptionFfi {
  final double feeRateSatVb;
  final BigInt feeSat;
  final BigInt amountToSweepSat;

  const BillSweepBTCOptionFfi({
    required this.feeRateSatVb,
    required this.feeSat,
    required this.amountToSweepSat,
  });

  @override
  int get hashCode =>
      feeRateSatVb.hashCode ^ feeSat.hashCode ^ amountToSweepSat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillSweepBTCOptionFfi &&
          runtimeType == other.runtimeType &&
          feeRateSatVb == other.feeRateSatVb &&
          feeSat == other.feeSat &&
          amountToSweepSat == other.amountToSweepSat;
}

class BillWaitingForPaymentStateFfi {
  final BillIdentParticipantFfi payer;
  final BillParticipantFfi payee;
  final BillWaitingStatePaymentDataFfi paymentData;

  const BillWaitingForPaymentStateFfi({
    required this.payer,
    required this.payee,
    required this.paymentData,
  });

  @override
  int get hashCode => payer.hashCode ^ payee.hashCode ^ paymentData.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillWaitingForPaymentStateFfi &&
          runtimeType == other.runtimeType &&
          payer == other.payer &&
          payee == other.payee &&
          paymentData == other.paymentData;
}

class BillWaitingForRecourseStateFfi {
  final BillParticipantFfi recourser;
  final BillIdentParticipantFfi recoursee;
  final BillWaitingStatePaymentDataFfi paymentData;

  const BillWaitingForRecourseStateFfi({
    required this.recourser,
    required this.recoursee,
    required this.paymentData,
  });

  @override
  int get hashCode =>
      recourser.hashCode ^ recoursee.hashCode ^ paymentData.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillWaitingForRecourseStateFfi &&
          runtimeType == other.runtimeType &&
          recourser == other.recourser &&
          recoursee == other.recoursee &&
          paymentData == other.paymentData;
}

class BillWaitingForSellStateFfi {
  final BillParticipantFfi buyer;
  final BillParticipantFfi seller;
  final BillWaitingStatePaymentDataFfi paymentData;

  const BillWaitingForSellStateFfi({
    required this.buyer,
    required this.seller,
    required this.paymentData,
  });

  @override
  int get hashCode => buyer.hashCode ^ seller.hashCode ^ paymentData.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillWaitingForSellStateFfi &&
          runtimeType == other.runtimeType &&
          buyer == other.buyer &&
          seller == other.seller &&
          paymentData == other.paymentData;
}

class BillWaitingStatePaymentDataFfi {
  final BigInt timeOfRequest;
  final String currency;
  final String sum;
  final String addressToPay;
  final String? txId;
  final bool inMempool;
  final BigInt confirmations;
  final BigInt? paymentDeadline;

  const BillWaitingStatePaymentDataFfi({
    required this.timeOfRequest,
    required this.currency,
    required this.sum,
    required this.addressToPay,
    this.txId,
    required this.inMempool,
    required this.confirmations,
    this.paymentDeadline,
  });

  @override
  int get hashCode =>
      timeOfRequest.hashCode ^
      currency.hashCode ^
      sum.hashCode ^
      addressToPay.hashCode ^
      txId.hashCode ^
      inMempool.hashCode ^
      confirmations.hashCode ^
      paymentDeadline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillWaitingStatePaymentDataFfi &&
          runtimeType == other.runtimeType &&
          timeOfRequest == other.timeOfRequest &&
          currency == other.currency &&
          sum == other.sum &&
          addressToPay == other.addressToPay &&
          txId == other.txId &&
          inMempool == other.inMempool &&
          confirmations == other.confirmations &&
          paymentDeadline == other.paymentDeadline;
}

enum BillsFilterRoleFfi { all, payer, payee, contingent }

class BillsResponse {
  final List<BitcreditBillFfi> bills;

  const BillsResponse({required this.bills});

  @override
  int get hashCode => bills.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillsResponse &&
          runtimeType == other.runtimeType &&
          bills == other.bills;
}

class BillsSearchFilter {
  final String? searchTerm;
  final DateRange? dateRange;
  final BillsFilterRoleFfi role;
  final List<String> participants;
  final String currency;

  const BillsSearchFilter({
    this.searchTerm,
    this.dateRange,
    required this.role,
    required this.participants,
    required this.currency,
  });

  @override
  int get hashCode =>
      searchTerm.hashCode ^
      dateRange.hashCode ^
      role.hashCode ^
      participants.hashCode ^
      currency.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillsSearchFilter &&
          runtimeType == other.runtimeType &&
          searchTerm == other.searchTerm &&
          dateRange == other.dateRange &&
          role == other.role &&
          participants == other.participants &&
          currency == other.currency;
}

class BillsSearchFilterPayload {
  final BillsSearchFilter filter;

  const BillsSearchFilterPayload({required this.filter});

  @override
  int get hashCode => filter.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BillsSearchFilterPayload &&
          runtimeType == other.runtimeType &&
          filter == other.filter;
}

class BitcreditBillFfi {
  final String id;
  final BillParticipantsFfi participants;
  final BillDataFfi data;
  final BillStatusFfi status;
  final BillStateFfi state;
  final BillCurrentWaitingStateFfi? currentWaitingState;
  final BillCallerActionsFfi actions;

  const BitcreditBillFfi({
    required this.id,
    required this.participants,
    required this.data,
    required this.status,
    required this.state,
    this.currentWaitingState,
    required this.actions,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      participants.hashCode ^
      data.hashCode ^
      status.hashCode ^
      state.hashCode ^
      currentWaitingState.hashCode ^
      actions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BitcreditBillFfi &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          participants == other.participants &&
          data == other.data &&
          status == other.status &&
          state == other.state &&
          currentWaitingState == other.currentWaitingState &&
          actions == other.actions;
}

class BitcreditBillPayload {
  final BigInt t;
  final String countryOfIssuing;
  final String cityOfIssuing;
  final String issueDate;
  final String maturityDate;
  final String payee;
  final String drawee;
  final String sum;
  final String currency;
  final String countryOfPayment;
  final String cityOfPayment;
  final List<String> fileUploadIds;

  const BitcreditBillPayload({
    required this.t,
    required this.countryOfIssuing,
    required this.cityOfIssuing,
    required this.issueDate,
    required this.maturityDate,
    required this.payee,
    required this.drawee,
    required this.sum,
    required this.currency,
    required this.countryOfPayment,
    required this.cityOfPayment,
    required this.fileUploadIds,
  });

  @override
  int get hashCode =>
      t.hashCode ^
      countryOfIssuing.hashCode ^
      cityOfIssuing.hashCode ^
      issueDate.hashCode ^
      maturityDate.hashCode ^
      payee.hashCode ^
      drawee.hashCode ^
      sum.hashCode ^
      currency.hashCode ^
      countryOfPayment.hashCode ^
      cityOfPayment.hashCode ^
      fileUploadIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BitcreditBillPayload &&
          runtimeType == other.runtimeType &&
          t == other.t &&
          countryOfIssuing == other.countryOfIssuing &&
          cityOfIssuing == other.cityOfIssuing &&
          issueDate == other.issueDate &&
          maturityDate == other.maturityDate &&
          payee == other.payee &&
          drawee == other.drawee &&
          sum == other.sum &&
          currency == other.currency &&
          countryOfPayment == other.countryOfPayment &&
          cityOfPayment == other.cityOfPayment &&
          fileUploadIds == other.fileUploadIds;
}

class DateRange {
  final String from;
  final String to;

  const DateRange({required this.from, required this.to});

  @override
  int get hashCode => from.hashCode ^ to.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DateRange &&
          runtimeType == other.runtimeType &&
          from == other.from &&
          to == other.to;
}

class EndorseBitcreditBillPayload {
  final String endorsee;
  final String billId;

  const EndorseBitcreditBillPayload({
    required this.endorsee,
    required this.billId,
  });

  @override
  int get hashCode => endorsee.hashCode ^ billId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EndorseBitcreditBillPayload &&
          runtimeType == other.runtimeType &&
          endorsee == other.endorsee &&
          billId == other.billId;
}

class EndorsementFfi {
  final LightBillParticipantFfi payToTheOrderOf;
  final LightSignedByFfi signed;
  final BigInt signingTimestamp;
  final PostalAddressFfi? signingAddress;

  const EndorsementFfi({
    required this.payToTheOrderOf,
    required this.signed,
    required this.signingTimestamp,
    this.signingAddress,
  });

  @override
  int get hashCode =>
      payToTheOrderOf.hashCode ^
      signed.hashCode ^
      signingTimestamp.hashCode ^
      signingAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EndorsementFfi &&
          runtimeType == other.runtimeType &&
          payToTheOrderOf == other.payToTheOrderOf &&
          signed == other.signed &&
          signingTimestamp == other.signingTimestamp &&
          signingAddress == other.signingAddress;
}

class EndorsementsResponse {
  final List<EndorsementFfi> endorsements;

  const EndorsementsResponse({required this.endorsements});

  @override
  int get hashCode => endorsements.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EndorsementsResponse &&
          runtimeType == other.runtimeType &&
          endorsements == other.endorsements;
}

class LightBillAnonParticipantFfi {
  final String nodeId;

  const LightBillAnonParticipantFfi({required this.nodeId});

  @override
  int get hashCode => nodeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LightBillAnonParticipantFfi &&
          runtimeType == other.runtimeType &&
          nodeId == other.nodeId;
}

class LightBillIdentParticipantFfi {
  final ContactTypeFfi t;
  final String name;
  final String nodeId;

  const LightBillIdentParticipantFfi({
    required this.t,
    required this.name,
    required this.nodeId,
  });

  @override
  int get hashCode => t.hashCode ^ name.hashCode ^ nodeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LightBillIdentParticipantFfi &&
          runtimeType == other.runtimeType &&
          t == other.t &&
          name == other.name &&
          nodeId == other.nodeId;
}

class LightBillIdentParticipantWithAddressFfi {
  final ContactTypeFfi t;
  final String name;
  final String nodeId;
  final PostalAddressFfi postalAddress;

  const LightBillIdentParticipantWithAddressFfi({
    required this.t,
    required this.name,
    required this.nodeId,
    required this.postalAddress,
  });

  @override
  int get hashCode =>
      t.hashCode ^ name.hashCode ^ nodeId.hashCode ^ postalAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LightBillIdentParticipantWithAddressFfi &&
          runtimeType == other.runtimeType &&
          t == other.t &&
          name == other.name &&
          nodeId == other.nodeId &&
          postalAddress == other.postalAddress;
}

@freezed
sealed class LightBillParticipantFfi with _$LightBillParticipantFfi {
  const LightBillParticipantFfi._();

  const factory LightBillParticipantFfi.anon(
    LightBillAnonParticipantFfi field0,
  ) = LightBillParticipantFfi_Anon;
  const factory LightBillParticipantFfi.ident(
    LightBillIdentParticipantWithAddressFfi field0,
  ) = LightBillParticipantFfi_Ident;
}

class LightBillSignatoryFfi {
  final String? name;
  final String nodeId;

  const LightBillSignatoryFfi({this.name, required this.nodeId});

  @override
  int get hashCode => name.hashCode ^ nodeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LightBillSignatoryFfi &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          nodeId == other.nodeId;
}

class LightBillsResponse {
  final List<LightBitcreditBillFfi> bills;

  const LightBillsResponse({required this.bills});

  @override
  int get hashCode => bills.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LightBillsResponse &&
          runtimeType == other.runtimeType &&
          bills == other.bills;
}

class LightBitcreditBillFfi {
  final String id;
  final LightBillIdentParticipantFfi drawee;
  final LightBillIdentParticipantFfi drawer;
  final LightBillParticipantFfi payee;
  final LightBillParticipantFfi? endorsee;
  final NotificationFfi? activeNotification;
  final String sum;
  final String currency;
  final String issueDate;
  final BigInt timeOfDrawing;
  final BigInt timeOfMaturity;
  final BigInt lastBlockTime;

  const LightBitcreditBillFfi({
    required this.id,
    required this.drawee,
    required this.drawer,
    required this.payee,
    this.endorsee,
    this.activeNotification,
    required this.sum,
    required this.currency,
    required this.issueDate,
    required this.timeOfDrawing,
    required this.timeOfMaturity,
    required this.lastBlockTime,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      drawee.hashCode ^
      drawer.hashCode ^
      payee.hashCode ^
      endorsee.hashCode ^
      activeNotification.hashCode ^
      sum.hashCode ^
      currency.hashCode ^
      issueDate.hashCode ^
      timeOfDrawing.hashCode ^
      timeOfMaturity.hashCode ^
      lastBlockTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LightBitcreditBillFfi &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          drawee == other.drawee &&
          drawer == other.drawer &&
          payee == other.payee &&
          endorsee == other.endorsee &&
          activeNotification == other.activeNotification &&
          sum == other.sum &&
          currency == other.currency &&
          issueDate == other.issueDate &&
          timeOfDrawing == other.timeOfDrawing &&
          timeOfMaturity == other.timeOfMaturity &&
          lastBlockTime == other.lastBlockTime;
}

class LightSignedByFfi {
  final LightBillParticipantFfi data;
  final LightBillSignatoryFfi? signatory;

  const LightSignedByFfi({required this.data, this.signatory});

  @override
  int get hashCode => data.hashCode ^ signatory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LightSignedByFfi &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          signatory == other.signatory;
}

class OfferToSellBitcreditBillPayload {
  final String buyer;
  final String billId;
  final String sum;
  final String currency;
  final String buyingDeadline;

  const OfferToSellBitcreditBillPayload({
    required this.buyer,
    required this.billId,
    required this.sum,
    required this.currency,
    required this.buyingDeadline,
  });

  @override
  int get hashCode =>
      buyer.hashCode ^
      billId.hashCode ^
      sum.hashCode ^
      currency.hashCode ^
      buyingDeadline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OfferToSellBitcreditBillPayload &&
          runtimeType == other.runtimeType &&
          buyer == other.buyer &&
          billId == other.billId &&
          sum == other.sum &&
          currency == other.currency &&
          buyingDeadline == other.buyingDeadline;
}

class PastEndorseeFfi {
  final LightBillIdentParticipantFfi payToTheOrderOf;
  final LightSignedByFfi signed;
  final BigInt signingTimestamp;
  final PostalAddressFfi? signingAddress;

  const PastEndorseeFfi({
    required this.payToTheOrderOf,
    required this.signed,
    required this.signingTimestamp,
    this.signingAddress,
  });

  @override
  int get hashCode =>
      payToTheOrderOf.hashCode ^
      signed.hashCode ^
      signingTimestamp.hashCode ^
      signingAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PastEndorseeFfi &&
          runtimeType == other.runtimeType &&
          payToTheOrderOf == other.payToTheOrderOf &&
          signed == other.signed &&
          signingTimestamp == other.signingTimestamp &&
          signingAddress == other.signingAddress;
}

class PastEndorseesResponse {
  final List<PastEndorseeFfi> pastEndorsees;

  const PastEndorseesResponse({required this.pastEndorsees});

  @override
  int get hashCode => pastEndorsees.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PastEndorseesResponse &&
          runtimeType == other.runtimeType &&
          pastEndorsees == other.pastEndorsees;
}

class PastPaymentDataPaymentFfi {
  final BigInt timeOfRequest;
  final BillIdentParticipantFfi payer;
  final BillParticipantFfi payee;
  final String currency;
  final String sum;
  final String addressToPay;
  final String? privateDescriptorToSpend;
  final PaymentStatusFfi status;

  const PastPaymentDataPaymentFfi({
    required this.timeOfRequest,
    required this.payer,
    required this.payee,
    required this.currency,
    required this.sum,
    required this.addressToPay,
    this.privateDescriptorToSpend,
    required this.status,
  });

  @override
  int get hashCode =>
      timeOfRequest.hashCode ^
      payer.hashCode ^
      payee.hashCode ^
      currency.hashCode ^
      sum.hashCode ^
      addressToPay.hashCode ^
      privateDescriptorToSpend.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PastPaymentDataPaymentFfi &&
          runtimeType == other.runtimeType &&
          timeOfRequest == other.timeOfRequest &&
          payer == other.payer &&
          payee == other.payee &&
          currency == other.currency &&
          sum == other.sum &&
          addressToPay == other.addressToPay &&
          privateDescriptorToSpend == other.privateDescriptorToSpend &&
          status == other.status;
}

class PastPaymentDataRecourseFfi {
  final BigInt timeOfRequest;
  final BillParticipantFfi recourser;
  final BillIdentParticipantFfi recoursee;
  final String currency;
  final String sum;
  final String addressToPay;
  final String? privateDescriptorToSpend;
  final PaymentStatusFfi status;

  const PastPaymentDataRecourseFfi({
    required this.timeOfRequest,
    required this.recourser,
    required this.recoursee,
    required this.currency,
    required this.sum,
    required this.addressToPay,
    this.privateDescriptorToSpend,
    required this.status,
  });

  @override
  int get hashCode =>
      timeOfRequest.hashCode ^
      recourser.hashCode ^
      recoursee.hashCode ^
      currency.hashCode ^
      sum.hashCode ^
      addressToPay.hashCode ^
      privateDescriptorToSpend.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PastPaymentDataRecourseFfi &&
          runtimeType == other.runtimeType &&
          timeOfRequest == other.timeOfRequest &&
          recourser == other.recourser &&
          recoursee == other.recoursee &&
          currency == other.currency &&
          sum == other.sum &&
          addressToPay == other.addressToPay &&
          privateDescriptorToSpend == other.privateDescriptorToSpend &&
          status == other.status;
}

class PastPaymentDataSellFfi {
  final BigInt timeOfRequest;
  final BillParticipantFfi buyer;
  final BillParticipantFfi seller;
  final String currency;
  final String sum;
  final String addressToPay;
  final String? privateDescriptorToSpend;
  final PaymentStatusFfi status;

  const PastPaymentDataSellFfi({
    required this.timeOfRequest,
    required this.buyer,
    required this.seller,
    required this.currency,
    required this.sum,
    required this.addressToPay,
    this.privateDescriptorToSpend,
    required this.status,
  });

  @override
  int get hashCode =>
      timeOfRequest.hashCode ^
      buyer.hashCode ^
      seller.hashCode ^
      currency.hashCode ^
      sum.hashCode ^
      addressToPay.hashCode ^
      privateDescriptorToSpend.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PastPaymentDataSellFfi &&
          runtimeType == other.runtimeType &&
          timeOfRequest == other.timeOfRequest &&
          buyer == other.buyer &&
          seller == other.seller &&
          currency == other.currency &&
          sum == other.sum &&
          addressToPay == other.addressToPay &&
          privateDescriptorToSpend == other.privateDescriptorToSpend &&
          status == other.status;
}

@freezed
sealed class PastPaymentResultFfi with _$PastPaymentResultFfi {
  const PastPaymentResultFfi._();

  const factory PastPaymentResultFfi.sell(PastPaymentDataSellFfi field0) =
      PastPaymentResultFfi_Sell;
  const factory PastPaymentResultFfi.payment(PastPaymentDataPaymentFfi field0) =
      PastPaymentResultFfi_Payment;
  const factory PastPaymentResultFfi.recourse(
    PastPaymentDataRecourseFfi field0,
  ) = PastPaymentResultFfi_Recourse;
}

class PastPaymentsResponse {
  final List<PastPaymentResultFfi> pastPayments;

  const PastPaymentsResponse({required this.pastPayments});

  @override
  int get hashCode => pastPayments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PastPaymentsResponse &&
          runtimeType == other.runtimeType &&
          pastPayments == other.pastPayments;
}

@freezed
sealed class PaymentStatusFfi with _$PaymentStatusFfi {
  const PaymentStatusFfi._();

  const factory PaymentStatusFfi.requested(BigInt field0) =
      PaymentStatusFfi_Requested;
  const factory PaymentStatusFfi.paid(BigInt field0) = PaymentStatusFfi_Paid;
  const factory PaymentStatusFfi.rejected(BigInt field0) =
      PaymentStatusFfi_Rejected;
  const factory PaymentStatusFfi.expired(BigInt field0) =
      PaymentStatusFfi_Expired;
}

class RejectActionBillPayload {
  final String billId;

  const RejectActionBillPayload({required this.billId});

  @override
  int get hashCode => billId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RejectActionBillPayload &&
          runtimeType == other.runtimeType &&
          billId == other.billId;
}

class RequestRecourseForAcceptancePayload {
  final String billId;
  final String recoursee;
  final String recourseDeadline;

  const RequestRecourseForAcceptancePayload({
    required this.billId,
    required this.recoursee,
    required this.recourseDeadline,
  });

  @override
  int get hashCode =>
      billId.hashCode ^ recoursee.hashCode ^ recourseDeadline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RequestRecourseForAcceptancePayload &&
          runtimeType == other.runtimeType &&
          billId == other.billId &&
          recoursee == other.recoursee &&
          recourseDeadline == other.recourseDeadline;
}

class RequestRecourseForPaymentPayload {
  final String billId;
  final String recoursee;
  final String currency;
  final String sum;
  final String recourseDeadline;

  const RequestRecourseForPaymentPayload({
    required this.billId,
    required this.recoursee,
    required this.currency,
    required this.sum,
    required this.recourseDeadline,
  });

  @override
  int get hashCode =>
      billId.hashCode ^
      recoursee.hashCode ^
      currency.hashCode ^
      sum.hashCode ^
      recourseDeadline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RequestRecourseForPaymentPayload &&
          runtimeType == other.runtimeType &&
          billId == other.billId &&
          recoursee == other.recoursee &&
          currency == other.currency &&
          sum == other.sum &&
          recourseDeadline == other.recourseDeadline;
}

class RequestToAcceptBitcreditBillPayload {
  final String billId;
  final String acceptanceDeadline;

  const RequestToAcceptBitcreditBillPayload({
    required this.billId,
    required this.acceptanceDeadline,
  });

  @override
  int get hashCode => billId.hashCode ^ acceptanceDeadline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RequestToAcceptBitcreditBillPayload &&
          runtimeType == other.runtimeType &&
          billId == other.billId &&
          acceptanceDeadline == other.acceptanceDeadline;
}

class RequestToMintBitcreditBillPayload {
  final String mintNode;
  final String billId;

  const RequestToMintBitcreditBillPayload({
    required this.mintNode,
    required this.billId,
  });

  @override
  int get hashCode => mintNode.hashCode ^ billId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RequestToMintBitcreditBillPayload &&
          runtimeType == other.runtimeType &&
          mintNode == other.mintNode &&
          billId == other.billId;
}

class RequestToPayAsMintBitcreditBillPayload {
  final String billId;
  final String currency;
  final String paymentDeadline;
  final String paymentAddress;

  const RequestToPayAsMintBitcreditBillPayload({
    required this.billId,
    required this.currency,
    required this.paymentDeadline,
    required this.paymentAddress,
  });

  @override
  int get hashCode =>
      billId.hashCode ^
      currency.hashCode ^
      paymentDeadline.hashCode ^
      paymentAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RequestToPayAsMintBitcreditBillPayload &&
          runtimeType == other.runtimeType &&
          billId == other.billId &&
          currency == other.currency &&
          paymentDeadline == other.paymentDeadline &&
          paymentAddress == other.paymentAddress;
}

class RequestToPayBitcreditBillPayload {
  final String billId;
  final String currency;
  final String paymentDeadline;

  const RequestToPayBitcreditBillPayload({
    required this.billId,
    required this.currency,
    required this.paymentDeadline,
  });

  @override
  int get hashCode =>
      billId.hashCode ^ currency.hashCode ^ paymentDeadline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RequestToPayBitcreditBillPayload &&
          runtimeType == other.runtimeType &&
          billId == other.billId &&
          currency == other.currency &&
          paymentDeadline == other.paymentDeadline;
}

class ResyncBillPayload {
  final String billId;
  final bool? fromNostr;

  const ResyncBillPayload({required this.billId, this.fromNostr});

  @override
  int get hashCode => billId.hashCode ^ fromNostr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResyncBillPayload &&
          runtimeType == other.runtimeType &&
          billId == other.billId &&
          fromNostr == other.fromNostr;
}

class ShareBillWithCourtPayload {
  final String billId;
  final String courtNodeId;

  const ShareBillWithCourtPayload({
    required this.billId,
    required this.courtNodeId,
  });

  @override
  int get hashCode => billId.hashCode ^ courtNodeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShareBillWithCourtPayload &&
          runtimeType == other.runtimeType &&
          billId == other.billId &&
          courtNodeId == other.courtNodeId;
}
