// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../data.dart';
import 'contact.dart';
import 'identity.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'company.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `try_from`

class AcceptCompanyInvitePayload {
  final String id;
  final String email;

  const AcceptCompanyInvitePayload({required this.id, required this.email});

  @override
  int get hashCode => id.hashCode ^ email.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AcceptCompanyInvitePayload &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          email == other.email;
}

class ChangeSignatoryEmailPayload {
  final String id;
  final String email;

  const ChangeSignatoryEmailPayload({required this.id, required this.email});

  @override
  int get hashCode => id.hashCode ^ email.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChangeSignatoryEmailPayload &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          email == other.email;
}

class CompaniesResponse {
  final List<CompanyFfi> companies;

  const CompaniesResponse({required this.companies});

  @override
  int get hashCode => companies.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompaniesResponse &&
          runtimeType == other.runtimeType &&
          companies == other.companies;
}

class CompanyConfirmEmailPayload {
  final String id;
  final String email;

  const CompanyConfirmEmailPayload({required this.id, required this.email});

  @override
  int get hashCode => id.hashCode ^ email.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompanyConfirmEmailPayload &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          email == other.email;
}

class CompanyFfi {
  final String id;
  final String name;
  final String? countryOfRegistration;
  final String? cityOfRegistration;
  final PostalAddressFfi postalAddress;
  final String email;
  final String? registrationNumber;
  final String? registrationDate;
  final FileFfi? proofOfRegistrationFile;
  final FileFfi? logoFile;
  final List<CompanySignatoryFfi> signatories;
  final BigInt creationTime;
  final CompanyStatusFfi status;

  const CompanyFfi({
    required this.id,
    required this.name,
    this.countryOfRegistration,
    this.cityOfRegistration,
    required this.postalAddress,
    required this.email,
    this.registrationNumber,
    this.registrationDate,
    this.proofOfRegistrationFile,
    this.logoFile,
    required this.signatories,
    required this.creationTime,
    required this.status,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      countryOfRegistration.hashCode ^
      cityOfRegistration.hashCode ^
      postalAddress.hashCode ^
      email.hashCode ^
      registrationNumber.hashCode ^
      registrationDate.hashCode ^
      proofOfRegistrationFile.hashCode ^
      logoFile.hashCode ^
      signatories.hashCode ^
      creationTime.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompanyFfi &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          countryOfRegistration == other.countryOfRegistration &&
          cityOfRegistration == other.cityOfRegistration &&
          postalAddress == other.postalAddress &&
          email == other.email &&
          registrationNumber == other.registrationNumber &&
          registrationDate == other.registrationDate &&
          proofOfRegistrationFile == other.proofOfRegistrationFile &&
          logoFile == other.logoFile &&
          signatories == other.signatories &&
          creationTime == other.creationTime &&
          status == other.status;
}

class CompanyKeysFfi {
  final String id;

  const CompanyKeysFfi({required this.id});

  @override
  int get hashCode => id.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompanyKeysFfi &&
          runtimeType == other.runtimeType &&
          id == other.id;
}

class CompanySignatoryFfi {
  final String nodeId;
  final CompanySignatoryStatusFfi status;

  const CompanySignatoryFfi({required this.nodeId, required this.status});

  @override
  int get hashCode => nodeId.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompanySignatoryFfi &&
          runtimeType == other.runtimeType &&
          nodeId == other.nodeId &&
          status == other.status;
}

@freezed
sealed class CompanySignatoryStatusFfi with _$CompanySignatoryStatusFfi {
  const CompanySignatoryStatusFfi._();

  const factory CompanySignatoryStatusFfi.invited({
    required BigInt ts,
    required String inviter,
  }) = CompanySignatoryStatusFfi_Invited;
  const factory CompanySignatoryStatusFfi.inviteAccepted({required BigInt ts}) =
      CompanySignatoryStatusFfi_InviteAccepted;
  const factory CompanySignatoryStatusFfi.inviteRejected({required BigInt ts}) =
      CompanySignatoryStatusFfi_InviteRejected;
  const factory CompanySignatoryStatusFfi.inviteAcceptedIdentityProven({
    required BigInt ts,
    required IdentityEmailConfirmationFfi confirmation,
  }) = CompanySignatoryStatusFfi_InviteAcceptedIdentityProven;
  const factory CompanySignatoryStatusFfi.removed({
    required BigInt ts,
    required String remover,
  }) = CompanySignatoryStatusFfi_Removed;
}

enum CompanyStatusFfi { invited, active, none }

class CompanyVerifyEmailPayload {
  final String id;
  final String confirmationCode;

  const CompanyVerifyEmailPayload({
    required this.id,
    required this.confirmationCode,
  });

  @override
  int get hashCode => id.hashCode ^ confirmationCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompanyVerifyEmailPayload &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          confirmationCode == other.confirmationCode;
}

class CreateCompanyPayload {
  final String id;
  final String name;
  final String? countryOfRegistration;
  final String? cityOfRegistration;
  final CreatePostalAddressFfi postalAddress;
  final String email;
  final String? registrationNumber;
  final String? registrationDate;
  final String? proofOfRegistrationFileUploadId;
  final String? logoFileUploadId;
  final String creatorEmail;

  const CreateCompanyPayload({
    required this.id,
    required this.name,
    this.countryOfRegistration,
    this.cityOfRegistration,
    required this.postalAddress,
    required this.email,
    this.registrationNumber,
    this.registrationDate,
    this.proofOfRegistrationFileUploadId,
    this.logoFileUploadId,
    required this.creatorEmail,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      countryOfRegistration.hashCode ^
      cityOfRegistration.hashCode ^
      postalAddress.hashCode ^
      email.hashCode ^
      registrationNumber.hashCode ^
      registrationDate.hashCode ^
      proofOfRegistrationFileUploadId.hashCode ^
      logoFileUploadId.hashCode ^
      creatorEmail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateCompanyPayload &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          countryOfRegistration == other.countryOfRegistration &&
          cityOfRegistration == other.cityOfRegistration &&
          postalAddress == other.postalAddress &&
          email == other.email &&
          registrationNumber == other.registrationNumber &&
          registrationDate == other.registrationDate &&
          proofOfRegistrationFileUploadId ==
              other.proofOfRegistrationFileUploadId &&
          logoFileUploadId == other.logoFileUploadId &&
          creatorEmail == other.creatorEmail;
}

class EditCompanyPayload {
  final String id;
  final String? name;
  final String? email;
  final String? postalAddressCountry;
  final String? postalAddressCity;
  final EditOptionalFieldModeFfi postalAddressZip;
  final String? postalAddressAddress;
  final EditOptionalFieldModeFfi countryOfRegistration;
  final EditOptionalFieldModeFfi cityOfRegistration;
  final EditOptionalFieldModeFfi registrationNumber;
  final EditOptionalFieldModeFfi registrationDate;
  final EditOptionalFieldModeFfi logoFileUploadId;
  final EditOptionalFieldModeFfi proofOfRegistrationFileUploadId;

  const EditCompanyPayload({
    required this.id,
    this.name,
    this.email,
    this.postalAddressCountry,
    this.postalAddressCity,
    required this.postalAddressZip,
    this.postalAddressAddress,
    required this.countryOfRegistration,
    required this.cityOfRegistration,
    required this.registrationNumber,
    required this.registrationDate,
    required this.logoFileUploadId,
    required this.proofOfRegistrationFileUploadId,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      email.hashCode ^
      postalAddressCountry.hashCode ^
      postalAddressCity.hashCode ^
      postalAddressZip.hashCode ^
      postalAddressAddress.hashCode ^
      countryOfRegistration.hashCode ^
      cityOfRegistration.hashCode ^
      registrationNumber.hashCode ^
      registrationDate.hashCode ^
      logoFileUploadId.hashCode ^
      proofOfRegistrationFileUploadId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditCompanyPayload &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          email == other.email &&
          postalAddressCountry == other.postalAddressCountry &&
          postalAddressCity == other.postalAddressCity &&
          postalAddressZip == other.postalAddressZip &&
          postalAddressAddress == other.postalAddressAddress &&
          countryOfRegistration == other.countryOfRegistration &&
          cityOfRegistration == other.cityOfRegistration &&
          registrationNumber == other.registrationNumber &&
          registrationDate == other.registrationDate &&
          logoFileUploadId == other.logoFileUploadId &&
          proofOfRegistrationFileUploadId ==
              other.proofOfRegistrationFileUploadId;
}

class InviteSignatoryPayload {
  final String id;
  final String signatoryNodeId;

  const InviteSignatoryPayload({
    required this.id,
    required this.signatoryNodeId,
  });

  @override
  int get hashCode => id.hashCode ^ signatoryNodeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InviteSignatoryPayload &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          signatoryNodeId == other.signatoryNodeId;
}

class ListSignatoriesResponse {
  final List<SignatoryResponse> signatories;

  const ListSignatoriesResponse({required this.signatories});

  @override
  int get hashCode => signatories.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListSignatoriesResponse &&
          runtimeType == other.runtimeType &&
          signatories == other.signatories;
}

class LocallyHideSignatoryPayload {
  final String id;
  final String signatoryNodeId;

  const LocallyHideSignatoryPayload({
    required this.id,
    required this.signatoryNodeId,
  });

  @override
  int get hashCode => id.hashCode ^ signatoryNodeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocallyHideSignatoryPayload &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          signatoryNodeId == other.signatoryNodeId;
}

class RemoveSignatoryPayload {
  final String id;
  final String signatoryNodeId;

  const RemoveSignatoryPayload({
    required this.id,
    required this.signatoryNodeId,
  });

  @override
  int get hashCode => id.hashCode ^ signatoryNodeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoveSignatoryPayload &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          signatoryNodeId == other.signatoryNodeId;
}

class ResyncCompanyPayload {
  final String nodeId;

  const ResyncCompanyPayload({required this.nodeId});

  @override
  int get hashCode => nodeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResyncCompanyPayload &&
          runtimeType == other.runtimeType &&
          nodeId == other.nodeId;
}

class SignatoryResponse {
  final ContactTypeFfi t;
  final String nodeId;
  final String name;
  final PostalAddressFfi? postalAddress;
  final FileFfi? avatarFile;
  final bool isLogical;
  final CompanySignatoryFfi signatory;

  const SignatoryResponse({
    required this.t,
    required this.nodeId,
    required this.name,
    this.postalAddress,
    this.avatarFile,
    required this.isLogical,
    required this.signatory,
  });

  @override
  int get hashCode =>
      t.hashCode ^
      nodeId.hashCode ^
      name.hashCode ^
      postalAddress.hashCode ^
      avatarFile.hashCode ^
      isLogical.hashCode ^
      signatory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SignatoryResponse &&
          runtimeType == other.runtimeType &&
          t == other.t &&
          nodeId == other.nodeId &&
          name == other.name &&
          postalAddress == other.postalAddress &&
          avatarFile == other.avatarFile &&
          isLogical == other.isLogical &&
          signatory == other.signatory;
}
