// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../data.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `try_from`

class ApproveContactSharePayload {
  final String pendingShareId;
  final bool addToContacts;
  final bool shareBack;

  const ApproveContactSharePayload({
    required this.pendingShareId,
    required this.addToContacts,
    required this.shareBack,
  });

  @override
  int get hashCode =>
      pendingShareId.hashCode ^ addToContacts.hashCode ^ shareBack.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApproveContactSharePayload &&
          runtimeType == other.runtimeType &&
          pendingShareId == other.pendingShareId &&
          addToContacts == other.addToContacts &&
          shareBack == other.shareBack;
}

class ContactFfi {
  final ContactTypeFfi t;
  final String nodeId;
  final String name;
  final String? email;
  final PostalAddressFfi? postalAddress;
  final String? dateOfBirthOrRegistration;
  final String? countryOfBirthOrRegistration;
  final String? cityOfBirthOrRegistration;
  final String? identificationNumber;
  final FileFfi? avatarFile;
  final FileFfi? proofDocumentFile;
  final List<String> nostrRelays;
  final bool isLogical;

  const ContactFfi({
    required this.t,
    required this.nodeId,
    required this.name,
    this.email,
    this.postalAddress,
    this.dateOfBirthOrRegistration,
    this.countryOfBirthOrRegistration,
    this.cityOfBirthOrRegistration,
    this.identificationNumber,
    this.avatarFile,
    this.proofDocumentFile,
    required this.nostrRelays,
    required this.isLogical,
  });

  @override
  int get hashCode =>
      t.hashCode ^
      nodeId.hashCode ^
      name.hashCode ^
      email.hashCode ^
      postalAddress.hashCode ^
      dateOfBirthOrRegistration.hashCode ^
      countryOfBirthOrRegistration.hashCode ^
      cityOfBirthOrRegistration.hashCode ^
      identificationNumber.hashCode ^
      avatarFile.hashCode ^
      proofDocumentFile.hashCode ^
      nostrRelays.hashCode ^
      isLogical.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactFfi &&
          runtimeType == other.runtimeType &&
          t == other.t &&
          nodeId == other.nodeId &&
          name == other.name &&
          email == other.email &&
          postalAddress == other.postalAddress &&
          dateOfBirthOrRegistration == other.dateOfBirthOrRegistration &&
          countryOfBirthOrRegistration == other.countryOfBirthOrRegistration &&
          cityOfBirthOrRegistration == other.cityOfBirthOrRegistration &&
          identificationNumber == other.identificationNumber &&
          avatarFile == other.avatarFile &&
          proofDocumentFile == other.proofDocumentFile &&
          nostrRelays == other.nostrRelays &&
          isLogical == other.isLogical;
}

enum ContactTypeFfi { person, company, anon }

class ContactsResponse {
  final List<ContactFfi> contacts;

  const ContactsResponse({required this.contacts});

  @override
  int get hashCode => contacts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContactsResponse &&
          runtimeType == other.runtimeType &&
          contacts == other.contacts;
}

class EditContactPayload {
  final String nodeId;
  final String? name;
  final String? email;
  final String? postalAddressCountry;
  final String? postalAddressCity;
  final EditOptionalFieldModeFfi postalAddressZip;
  final String? postalAddressAddress;
  final EditOptionalFieldModeFfi dateOfBirthOrRegistration;
  final EditOptionalFieldModeFfi countryOfBirthOrRegistration;
  final EditOptionalFieldModeFfi cityOfBirthOrRegistration;
  final EditOptionalFieldModeFfi identificationNumber;
  final EditOptionalFieldModeFfi avatarFileUploadId;
  final EditOptionalFieldModeFfi proofDocumentFileUploadId;

  const EditContactPayload({
    required this.nodeId,
    this.name,
    this.email,
    this.postalAddressCountry,
    this.postalAddressCity,
    required this.postalAddressZip,
    this.postalAddressAddress,
    required this.dateOfBirthOrRegistration,
    required this.countryOfBirthOrRegistration,
    required this.cityOfBirthOrRegistration,
    required this.identificationNumber,
    required this.avatarFileUploadId,
    required this.proofDocumentFileUploadId,
  });

  @override
  int get hashCode =>
      nodeId.hashCode ^
      name.hashCode ^
      email.hashCode ^
      postalAddressCountry.hashCode ^
      postalAddressCity.hashCode ^
      postalAddressZip.hashCode ^
      postalAddressAddress.hashCode ^
      dateOfBirthOrRegistration.hashCode ^
      countryOfBirthOrRegistration.hashCode ^
      cityOfBirthOrRegistration.hashCode ^
      identificationNumber.hashCode ^
      avatarFileUploadId.hashCode ^
      proofDocumentFileUploadId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditContactPayload &&
          runtimeType == other.runtimeType &&
          nodeId == other.nodeId &&
          name == other.name &&
          email == other.email &&
          postalAddressCountry == other.postalAddressCountry &&
          postalAddressCity == other.postalAddressCity &&
          postalAddressZip == other.postalAddressZip &&
          postalAddressAddress == other.postalAddressAddress &&
          dateOfBirthOrRegistration == other.dateOfBirthOrRegistration &&
          countryOfBirthOrRegistration == other.countryOfBirthOrRegistration &&
          cityOfBirthOrRegistration == other.cityOfBirthOrRegistration &&
          identificationNumber == other.identificationNumber &&
          avatarFileUploadId == other.avatarFileUploadId &&
          proofDocumentFileUploadId == other.proofDocumentFileUploadId;
}

class NewContactPayload {
  final BigInt t;
  final String nodeId;
  final String name;
  final String? email;
  final CreatePostalAddressFfi? postalAddress;
  final String? dateOfBirthOrRegistration;
  final String? countryOfBirthOrRegistration;
  final String? cityOfBirthOrRegistration;
  final String? identificationNumber;
  final String? avatarFileUploadId;
  final String? proofDocumentFileUploadId;

  const NewContactPayload({
    required this.t,
    required this.nodeId,
    required this.name,
    this.email,
    this.postalAddress,
    this.dateOfBirthOrRegistration,
    this.countryOfBirthOrRegistration,
    this.cityOfBirthOrRegistration,
    this.identificationNumber,
    this.avatarFileUploadId,
    this.proofDocumentFileUploadId,
  });

  @override
  int get hashCode =>
      t.hashCode ^
      nodeId.hashCode ^
      name.hashCode ^
      email.hashCode ^
      postalAddress.hashCode ^
      dateOfBirthOrRegistration.hashCode ^
      countryOfBirthOrRegistration.hashCode ^
      cityOfBirthOrRegistration.hashCode ^
      identificationNumber.hashCode ^
      avatarFileUploadId.hashCode ^
      proofDocumentFileUploadId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewContactPayload &&
          runtimeType == other.runtimeType &&
          t == other.t &&
          nodeId == other.nodeId &&
          name == other.name &&
          email == other.email &&
          postalAddress == other.postalAddress &&
          dateOfBirthOrRegistration == other.dateOfBirthOrRegistration &&
          countryOfBirthOrRegistration == other.countryOfBirthOrRegistration &&
          cityOfBirthOrRegistration == other.cityOfBirthOrRegistration &&
          identificationNumber == other.identificationNumber &&
          avatarFileUploadId == other.avatarFileUploadId &&
          proofDocumentFileUploadId == other.proofDocumentFileUploadId;
}

class PendingContactShareFfi {
  final String id;
  final String nodeId;
  final ContactFfi contact;
  final String senderNodeId;
  final String receiverNodeId;
  final BigInt receivedAt;

  const PendingContactShareFfi({
    required this.id,
    required this.nodeId,
    required this.contact,
    required this.senderNodeId,
    required this.receiverNodeId,
    required this.receivedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      nodeId.hashCode ^
      contact.hashCode ^
      senderNodeId.hashCode ^
      receiverNodeId.hashCode ^
      receivedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingContactShareFfi &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          nodeId == other.nodeId &&
          contact == other.contact &&
          senderNodeId == other.senderNodeId &&
          receiverNodeId == other.receiverNodeId &&
          receivedAt == other.receivedAt;
}

class PendingContactSharesResponse {
  final List<PendingContactShareFfi> pendingShares;

  const PendingContactSharesResponse({required this.pendingShares});

  @override
  int get hashCode => pendingShares.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingContactSharesResponse &&
          runtimeType == other.runtimeType &&
          pendingShares == other.pendingShares;
}

class SearchContactsPayload {
  final String searchTerm;
  final bool? includeLogical;
  final bool? includeContact;

  const SearchContactsPayload({
    required this.searchTerm,
    this.includeLogical,
    this.includeContact,
  });

  @override
  int get hashCode =>
      searchTerm.hashCode ^ includeLogical.hashCode ^ includeContact.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchContactsPayload &&
          runtimeType == other.runtimeType &&
          searchTerm == other.searchTerm &&
          includeLogical == other.includeLogical &&
          includeContact == other.includeContact;
}
