// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../data.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `try_from`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `from_identity`

class ChangeIdentityEmailPayload {
  final String email;

  const ChangeIdentityEmailPayload({required this.email});

  @override
  int get hashCode => email.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChangeIdentityEmailPayload &&
          runtimeType == other.runtimeType &&
          email == other.email;
}

class ChangeIdentityPayload {
  final String? name;
  final String? postalAddressCountry;
  final String? postalAddressCity;
  final EditOptionalFieldModeFfi postalAddressZip;
  final String? postalAddressAddress;
  final EditOptionalFieldModeFfi dateOfBirth;
  final EditOptionalFieldModeFfi countryOfBirth;
  final EditOptionalFieldModeFfi cityOfBirth;
  final EditOptionalFieldModeFfi identificationNumber;
  final EditOptionalFieldModeFfi profilePictureFileUploadId;
  final EditOptionalFieldModeFfi identityDocumentFileUploadId;

  const ChangeIdentityPayload({
    this.name,
    this.postalAddressCountry,
    this.postalAddressCity,
    required this.postalAddressZip,
    this.postalAddressAddress,
    required this.dateOfBirth,
    required this.countryOfBirth,
    required this.cityOfBirth,
    required this.identificationNumber,
    required this.profilePictureFileUploadId,
    required this.identityDocumentFileUploadId,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      postalAddressCountry.hashCode ^
      postalAddressCity.hashCode ^
      postalAddressZip.hashCode ^
      postalAddressAddress.hashCode ^
      dateOfBirth.hashCode ^
      countryOfBirth.hashCode ^
      cityOfBirth.hashCode ^
      identificationNumber.hashCode ^
      profilePictureFileUploadId.hashCode ^
      identityDocumentFileUploadId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChangeIdentityPayload &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          postalAddressCountry == other.postalAddressCountry &&
          postalAddressCity == other.postalAddressCity &&
          postalAddressZip == other.postalAddressZip &&
          postalAddressAddress == other.postalAddressAddress &&
          dateOfBirth == other.dateOfBirth &&
          countryOfBirth == other.countryOfBirth &&
          cityOfBirth == other.cityOfBirth &&
          identificationNumber == other.identificationNumber &&
          profilePictureFileUploadId == other.profilePictureFileUploadId &&
          identityDocumentFileUploadId == other.identityDocumentFileUploadId;
}

class ConfirmEmailPayload {
  final String email;

  const ConfirmEmailPayload({required this.email});

  @override
  int get hashCode => email.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfirmEmailPayload &&
          runtimeType == other.runtimeType &&
          email == other.email;
}

class IdentityEmailConfirmationFfi {
  final String signature;
  final String witness;
  final String nodeId;
  final String? companyNodeId;
  final String email;
  final BigInt createdAt;

  const IdentityEmailConfirmationFfi({
    required this.signature,
    required this.witness,
    required this.nodeId,
    this.companyNodeId,
    required this.email,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      signature.hashCode ^
      witness.hashCode ^
      nodeId.hashCode ^
      companyNodeId.hashCode ^
      email.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityEmailConfirmationFfi &&
          runtimeType == other.runtimeType &&
          signature == other.signature &&
          witness == other.witness &&
          nodeId == other.nodeId &&
          companyNodeId == other.companyNodeId &&
          email == other.email &&
          createdAt == other.createdAt;
}

class IdentityFfi {
  final IdentityTypeFfi t;
  final String nodeId;
  final String name;
  final String? email;
  final String bitcoinPublicKey;
  final String npub;
  final OptionalPostalAddressFfi postalAddress;
  final String? dateOfBirth;
  final String? countryOfBirth;
  final String? cityOfBirth;
  final String? identificationNumber;
  final FileFfi? profilePictureFile;
  final FileFfi? identityDocumentFile;
  final List<String> nostrRelays;

  const IdentityFfi({
    required this.t,
    required this.nodeId,
    required this.name,
    this.email,
    required this.bitcoinPublicKey,
    required this.npub,
    required this.postalAddress,
    this.dateOfBirth,
    this.countryOfBirth,
    this.cityOfBirth,
    this.identificationNumber,
    this.profilePictureFile,
    this.identityDocumentFile,
    required this.nostrRelays,
  });

  @override
  int get hashCode =>
      t.hashCode ^
      nodeId.hashCode ^
      name.hashCode ^
      email.hashCode ^
      bitcoinPublicKey.hashCode ^
      npub.hashCode ^
      postalAddress.hashCode ^
      dateOfBirth.hashCode ^
      countryOfBirth.hashCode ^
      cityOfBirth.hashCode ^
      identificationNumber.hashCode ^
      profilePictureFile.hashCode ^
      identityDocumentFile.hashCode ^
      nostrRelays.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IdentityFfi &&
          runtimeType == other.runtimeType &&
          t == other.t &&
          nodeId == other.nodeId &&
          name == other.name &&
          email == other.email &&
          bitcoinPublicKey == other.bitcoinPublicKey &&
          npub == other.npub &&
          postalAddress == other.postalAddress &&
          dateOfBirth == other.dateOfBirth &&
          countryOfBirth == other.countryOfBirth &&
          cityOfBirth == other.cityOfBirth &&
          identificationNumber == other.identificationNumber &&
          profilePictureFile == other.profilePictureFile &&
          identityDocumentFile == other.identityDocumentFile &&
          nostrRelays == other.nostrRelays;
}

enum IdentityTypeFfi { ident, anon }

class NewIdentityPayload {
  final BigInt t;
  final String name;
  final String? email;
  final CreateOptionalPostalAddressFfi postalAddress;
  final String? dateOfBirth;
  final String? countryOfBirth;
  final String? cityOfBirth;
  final String? identificationNumber;
  final String? profilePictureFileUploadId;
  final String? identityDocumentFileUploadId;

  const NewIdentityPayload({
    required this.t,
    required this.name,
    this.email,
    required this.postalAddress,
    this.dateOfBirth,
    this.countryOfBirth,
    this.cityOfBirth,
    this.identificationNumber,
    this.profilePictureFileUploadId,
    this.identityDocumentFileUploadId,
  });

  @override
  int get hashCode =>
      t.hashCode ^
      name.hashCode ^
      email.hashCode ^
      postalAddress.hashCode ^
      dateOfBirth.hashCode ^
      countryOfBirth.hashCode ^
      cityOfBirth.hashCode ^
      identificationNumber.hashCode ^
      profilePictureFileUploadId.hashCode ^
      identityDocumentFileUploadId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewIdentityPayload &&
          runtimeType == other.runtimeType &&
          t == other.t &&
          name == other.name &&
          email == other.email &&
          postalAddress == other.postalAddress &&
          dateOfBirth == other.dateOfBirth &&
          countryOfBirth == other.countryOfBirth &&
          cityOfBirth == other.cityOfBirth &&
          identificationNumber == other.identificationNumber &&
          profilePictureFileUploadId == other.profilePictureFileUploadId &&
          identityDocumentFileUploadId == other.identityDocumentFileUploadId;
}

/// Response for a private key seeed backup
class SeedPhrase {
  /// The seed phrase of the current private key
  final String seedPhrase;

  const SeedPhrase({required this.seedPhrase});

  @override
  int get hashCode => seedPhrase.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SeedPhrase &&
          runtimeType == other.runtimeType &&
          seedPhrase == other.seedPhrase;
}

class ShareCompanyContactTo {
  /// The node id of the identity to share the contact details to
  final String recipient;

  /// The node id of the company to share the contact details for
  final String companyId;

  const ShareCompanyContactTo({
    required this.recipient,
    required this.companyId,
  });

  @override
  int get hashCode => recipient.hashCode ^ companyId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShareCompanyContactTo &&
          runtimeType == other.runtimeType &&
          recipient == other.recipient &&
          companyId == other.companyId;
}

class ShareContactTo {
  /// The node id of the identity to share the contact details to
  final String recipient;

  const ShareContactTo({required this.recipient});

  @override
  int get hashCode => recipient.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShareContactTo &&
          runtimeType == other.runtimeType &&
          recipient == other.recipient;
}

class SwitchIdentity {
  final SwitchIdentityTypeFfi? t;
  final String nodeId;

  const SwitchIdentity({this.t, required this.nodeId});

  @override
  int get hashCode => t.hashCode ^ nodeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwitchIdentity &&
          runtimeType == other.runtimeType &&
          t == other.t &&
          nodeId == other.nodeId;
}

enum SwitchIdentityTypeFfi { person, company }

class VerifyEmailPayload {
  final String confirmationCode;

  const VerifyEmailPayload({required this.confirmationCode});

  @override
  int get hashCode => confirmationCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerifyEmailPayload &&
          runtimeType == other.runtimeType &&
          confirmationCode == other.confirmationCode;
}
