// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'mint.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`

class MintOfferFfi {
  final String mintRequestId;
  final String keysetId;
  final BigInt expirationTimestamp;
  final String discountedSum;
  final String? proofs;
  final bool proofsSpent;

  const MintOfferFfi({
    required this.mintRequestId,
    required this.keysetId,
    required this.expirationTimestamp,
    required this.discountedSum,
    this.proofs,
    required this.proofsSpent,
  });

  @override
  int get hashCode =>
      mintRequestId.hashCode ^
      keysetId.hashCode ^
      expirationTimestamp.hashCode ^
      discountedSum.hashCode ^
      proofs.hashCode ^
      proofsSpent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MintOfferFfi &&
          runtimeType == other.runtimeType &&
          mintRequestId == other.mintRequestId &&
          keysetId == other.keysetId &&
          expirationTimestamp == other.expirationTimestamp &&
          discountedSum == other.discountedSum &&
          proofs == other.proofs &&
          proofsSpent == other.proofsSpent;
}

class MintRequestFfi {
  final String requesterNodeId;
  final String billId;
  final String mintNodeId;
  final String mintRequestId;
  final BigInt timestamp;
  final MintRequestStatusFfi status;

  const MintRequestFfi({
    required this.requesterNodeId,
    required this.billId,
    required this.mintNodeId,
    required this.mintRequestId,
    required this.timestamp,
    required this.status,
  });

  @override
  int get hashCode =>
      requesterNodeId.hashCode ^
      billId.hashCode ^
      mintNodeId.hashCode ^
      mintRequestId.hashCode ^
      timestamp.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MintRequestFfi &&
          runtimeType == other.runtimeType &&
          requesterNodeId == other.requesterNodeId &&
          billId == other.billId &&
          mintNodeId == other.mintNodeId &&
          mintRequestId == other.mintRequestId &&
          timestamp == other.timestamp &&
          status == other.status;
}

class MintRequestStateFfi {
  final MintRequestFfi request;
  final MintOfferFfi? offer;

  const MintRequestStateFfi({required this.request, this.offer});

  @override
  int get hashCode => request.hashCode ^ offer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MintRequestStateFfi &&
          runtimeType == other.runtimeType &&
          request == other.request &&
          offer == other.offer;
}

class MintRequestStateResponse {
  final List<MintRequestStateFfi> requestStates;

  const MintRequestStateResponse({required this.requestStates});

  @override
  int get hashCode => requestStates.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MintRequestStateResponse &&
          runtimeType == other.runtimeType &&
          requestStates == other.requestStates;
}

@freezed
sealed class MintRequestStatusFfi with _$MintRequestStatusFfi {
  const MintRequestStatusFfi._();

  const factory MintRequestStatusFfi.pending() = MintRequestStatusFfi_Pending;
  const factory MintRequestStatusFfi.denied({required BigInt timestamp}) =
      MintRequestStatusFfi_Denied;
  const factory MintRequestStatusFfi.offered() = MintRequestStatusFfi_Offered;
  const factory MintRequestStatusFfi.accepted() = MintRequestStatusFfi_Accepted;
  const factory MintRequestStatusFfi.mintingEnabled() =
      MintRequestStatusFfi_MintingEnabled;
  const factory MintRequestStatusFfi.rejected({required BigInt timestamp}) =
      MintRequestStatusFfi_Rejected;
  const factory MintRequestStatusFfi.cancelled({required BigInt timestamp}) =
      MintRequestStatusFfi_Cancelled;
  const factory MintRequestStatusFfi.expired({required BigInt timestamp}) =
      MintRequestStatusFfi_Expired;
}
