// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

class NotificationFfi {
  final String id;
  final String? nodeId;
  final NotificationTypeFfi notificationType;
  final String? referenceId;
  final String description;
  final String datetime;
  final bool active;
  final NotificationLevelFfi level;
  final String? payload;

  const NotificationFfi({
    required this.id,
    this.nodeId,
    required this.notificationType,
    this.referenceId,
    required this.description,
    required this.datetime,
    required this.active,
    required this.level,
    this.payload,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      nodeId.hashCode ^
      notificationType.hashCode ^
      referenceId.hashCode ^
      description.hashCode ^
      datetime.hashCode ^
      active.hashCode ^
      level.hashCode ^
      payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotificationFfi &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          nodeId == other.nodeId &&
          notificationType == other.notificationType &&
          referenceId == other.referenceId &&
          description == other.description &&
          datetime == other.datetime &&
          active == other.active &&
          level == other.level &&
          payload == other.payload;
}

enum NotificationLevelFfi { informational, actionRequired }

class NotificationStatusFfi {
  final String nodeId;
  final bool active;

  const NotificationStatusFfi({required this.nodeId, required this.active});

  @override
  int get hashCode => nodeId.hashCode ^ active.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NotificationStatusFfi &&
          runtimeType == other.runtimeType &&
          nodeId == other.nodeId &&
          active == other.active;
}

enum NotificationTypeFfi { general, company, bill, contact }
